### ISSUE TITLE
500 page styling

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#150]
**Summary:**
I would like these pages to fit on one screen with no scrolling on an iPad (retina display) resolution or higher. 

First, remove the line:
For immediate help, contact support.

and move up remaning text and back to dashboard button

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir can you please send me these 500 and 404 templates directory where i can locate these. 

Also these chnages have to implement on both 500 error and 404 error pages?

**Comment by rodolfomartinez** [comment]
@KPSbuttar - we only require styling for 500 for the time being. 

A quick look through the code revealed this - does it help?



def server_error(request, template_name='shared_home/http_500.html'):
21 | response = render(request, 'shared_home/http_500.html',{})
22 | response.status_code = 500
23 | return response
24

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its done
