### ISSUE TITLE
View Details for Clients and Members

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#155]
**Summary:**
When clicking the view details button the files for clients and members are difficult to read. Please look at this drawing - the field titles should be smaller than the data, and bolded, and the "column" that displays data should be wider to allow for two fields on the same row at iPad Retina resolution.

Client View More: http://london.o55.me/en/clients/summary/detail/23060/
Member View More: http://london.o55.me/en/members/summary/detail/6122/?page=1

![763d2810-5b01-490c-9d09-9204d6f09e7f](https://user-images.githubusercontent.com/7537946/39851054-cbe08904-53e2-11e8-8a2c-017e3f162b84.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its Complete you can review now all 3 modules retrive full details VIEW modified.
