### ISSUE TITLE
Alert and task notifications

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#162]
**Summary:**
As we discussed, here is a concept to place icons for tasks and alerts so that the user always knows if there is an item that needs to be actioned. As the system expands over the time, things like messages/emails, support tickets, etc. could also be added
![89fa767f-a463-4b6b-8b76-e285eb7ca0ab](https://user-images.githubusercontent.com/7537946/39953685-ffa359a4-557e-11e8-89fe-aa21fb18c2fb.jpeg)

**Comment by bartmika** [comment]
This can be done and it's preferable we get it done now vs after we deploy.

Can you get Kanwar to create the GUI in the InThought theme?

**Comment by rodolfomartinez** [comment]
@KPSbuttar - can you please add these alert icons in the top right next to the menu icon InThought theme, and then post URL so we can integrate into this project?

**Comment by bartmika** [comment]
@rodolfomartinez @KPSbuttar What is the status of this ticket?

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir finally this is completed. Thanks
