### ISSUE TITLE
Update List Icon Colour

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#169]
**Summary:**
At these URLs
https://london.workery.ca/en/clients/summary/
https://london.workery.ca/en/jobs/summary/
https://london.workery.ca/en/partners/summary/
https://london.workery.ca/en/teams/
https://london.workery.ca/en/jobs/summary/

The list icon should be blue and not orange

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir, its done
