### ISSUE TITLE
Upgrade to Font Awesome 5

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#171]
**Summary:**
Are we using Font Awesome 5? If not, should we assign this task to kanwar?

**Comment by bartmika** [comment]
@KPSbuttar May you please update the InThought theme to use the latest fontawesome theme and tell me what I need to upgrade for this project, I can help do that.

@rodolfomartinez FYI

**Comment by rodolfomartinez** [comment]
Already using 5.0.4
