### ISSUE TITLE
Add Skill Set - Insurance Requirement

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#176]
**Summary:**
Currently, this is a text field. Can we make it a dropdown instead? It should have the following options:
CGL - $2 Million Minimum
O55 CGL 
OPCF 6A - $2 Million Minimum

**Comment by bartmika** [comment]
@rodolfomartinez Can it be possible that some skillsets have more then one insurance requirements?

**Comment by rodolfomartinez** [comment]
Currently each skillset only has 1 insurance. We so not have any requiring more than one insurance
