### ISSUE TITLE
Scale down client/member summary template

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#177]
**Summary:**
At this URL (this is a member summary; should apply to clients and team members as well)
https://london.workery.ca/en/members/summary/detail/6120/lite/?page=1

Please scale down the rectangular area so that it fits on one screen without scrolling at iPad or higher resolution. Currently I need to scroll down a bit when viewing in 1080p. A reduction of 20% should do.

**Comment by rodolfomartinez** [comment]
@KPSbuttar 
![78a16b3f-69ed-47b5-9d03-0225e452f745](https://user-images.githubusercontent.com/7537946/40362410-78a14762-5d9a-11e8-9f43-07ba3bd631c0.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir you can review now. Thanks!
