### ISSUE TITLE
Add/Edit Member - Hourly Salary Desired

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#181]
**Summary:**

This field should have the label changed to
Hourly Rate:

The field itself can be 1/3 of the current size, and validation should only allow the user to type in numbers, commas and decimals.

**Comment by bartmika** [comment]
Hi @KPSbuttar, here is the URL you can use: 
https://workery.ca/en/api/associates/validate

Also here is the jQuery code which you can use to call the validation:

https://github.com/over55/workery-django/blob/master/workery/templates/tenant_api/members_api_js.html#L87

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika SO fir this ticket UI html, js part is done. only Currency API validation need to check by @bartmika Thanks
