### ISSUE TITLE
Add/Edit Member

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#182]
**Summary:**
Eventually we are going to need a way to record that the associate has agreed to relevant organizational agreements - code of conduct, harassment policy, etc.

How should we implement this? Keep in mind that different orgs could have different requirements

**Comment by bartmika** [comment]
@rodolfomartinez Please call to discuss.

**Comment by rodolfomartinez** [comment]
We can discuss later tonight

**Comment by bartmika** [comment]
As per our discussion. Closing issue.
