### ISSUE TITLE
Add Team member/Staff - Country dropdown blank

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#186]
**Summary:**
At this URL 
https://london.workery.ca/en/teams/create/

country dropdown is blank when trying to add a staff member - however I can still add the person

**Comment by bartmika** [comment]
@rodolfomartinez this is an issue that @KPSbuttar has to handle.

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its done
