### ISSUE TITLE
fa-external-link

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#191]
Why is when I replace the code ``<i class="fas fa-link">`` with ``<i class="fas fa-external-link-square"></i>`` that new font awesome icon not work?

Note:
* https://fontawesome.com/v4.7.0/icon/external-link/

@rodolfomartinez FYI

**Comment by KPSbuttar** [comment]
@bartmika Hi sir, yes you need to use fontawesome version 5 icon code. So basically currently which you are using is from version 4 so you need use this one `<i class="fas fa-external-link-alt"></i>` which is from 
 fontawesome upgraded version 5. Thanks

**Comment by KPSbuttar** [comment]
I hope this helps.
