### ISSUE TITLE
Login Page no longer working?

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#192]
Hi @KPSbuttar , recently I attempted to login and the logins are always failing. Could you check the login GUI code and see if there's anything that could be causing this? The login stopped working after a recent change you made.

@rodolfomartinez Highest priority.

**Comment by KPSbuttar** [comment]
@bartmika Hi sir Please CHECK IF its working ok now.

**Comment by bartmika** [comment]
That fixed it! Thank you @KPSbuttar for the speedy fix!!
