### ISSUE TITLE
Add financial input to customer satisfaction screen

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#193]
Todo

**Comment by bartmika** [comment]
Confirmed I see this. Will work on this now.

**Comment by bartmika** [comment]
1. If no HST, give red texted warning
2. IF no quote, make it equal to calculated total
3. Create "ServiceFee" objects that work similar to tags
4. date -=> Invoice date
5.quote -> money
6. labour, materials, hst -> money
7. total -> summation of labour, material, hst
