### ISSUE TITLE
Password Validation not working on Safari

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#196]
**Summary:**
Password validation UI just shows boxes on Safari

<img width="685" alt="screen shot 2018-05-17 at 11 45 43 am" src="https://user-images.githubusercontent.com/7537946/40188576-3ffb444c-59c8-11e8-9861-1a389669d211.png">

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its fixed sir please refresh sharedbase css before you review this. Thanks
