### ISSUE TITLE
Tag UI (skillsets etc) not working in edit mode in Safari

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#197]
**Summary:**
When editing a member, tags are displayed as dropdown in Safari on iPad and as a textfield box in Safari on Mac computer, and cannot be edited. Also, new tags cannot be added. 

Appears to work fine on Chrome.
<img width="620" alt="screen shot 2018-05-17 at 1 34 15 pm" src="https://user-images.githubusercontent.com/7537946/40194220-a479b106-59d7-11e8-9b1e-bc0c718e2984.png">

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika This will be fixed i guess lets see can you please redeply server make sure html head section updated with latest changes. Thanks.

@rodolfomartinez Please review after redeployment sir!

**Comment by bartmika** [comment]
I confirm this has been closed.
