### ISSUE TITLE
ETL - Completion Date

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#199]
**SUmmary:**
Many jobs are importing with no completion date showing them as open. For historical jobs, can we import with the "Paid Date" being the value for "Completion Date" so that all historical jobs are closed?

I will be sending a new copy of the database via email to facilitate this process.

**Comment by rodolfomartinez** [comment]
@bartmika this issue is still persistent. Current ETL shows 2700+ open jobs

**Comment by bartmika** [comment]
![screen shot 2018-05-24 at 11 39 02 pm](https://user-images.githubusercontent.com/5767602/40525018-b1b56c0a-5fab-11e8-8712-9996c7b4ba8e.png)

Is this complete?

**Comment by rodolfomartinez** [comment]
Confirmed that this is due to error in data and not the app. @bartmika - can we simply insert completion dates for those three jobs?

**Comment by rodolfomartinez** [comment]
@bartmika - the job count is up to 297 now
![b4c5c539-9e3c-4206-b998-b1ed6da9a735](https://user-images.githubusercontent.com/7537946/40626700-3cbc7710-6288-11e8-9fcf-de8724906d18.png)

**Comment by bartmika** [comment]
Hi Rodolfo,

Would it be possible if instead we 'archived' all legacy sales?
