### ISSUE TITLE
Settings -> Skills -> Update Skills -> Missing Validation

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#207]

**Comment by rodolfomartinez** [comment]
@bartmika can you post a sample URL?

**Comment by rodolfomartinez** [comment]
@KPSbuttar - I believe it is at this URL
https://london.workery.ca/en/settings/skill_set/1/

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez All done sir, JS and html validations are completed. Now only API needs to update. Thanks

**Comment by bartmika** [comment]
![screen shot 2018-05-29 at 7 44 18 pm](https://user-images.githubusercontent.com/5767602/40691182-b491e130-6378-11e8-8b4c-fd217a54dc61.png)

@KPSbuttar Hi Kanwar, I've implemented the stricter validation, may you please add the error message to the insurance requirement. Once you accomplish this, this issue can be closed.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its done.
