### ISSUE TITLE
Google Search Console

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#217]
Hi Rodolfo,

In your [Google Search Console](https://www.google.com/webmasters/tools/home) may you please generate an ID? Please only put https://workery.ca - do not forget the *S* in httpS. If you would like me to do it on my end, let me know?

Thanks!

**Comment by rodolfomartinez** [comment]
@bartmika - this has been created for workery.ca

**Comment by bartmika** [comment]
Hi Rodolfo, I deleted the domain info in **DigitalOcean**, this was because **Lets Encrypt** gave me somesort of error. Can you try adding it again?

**Comment by rodolfomartinez** [comment]
@bartmika not sure exactly what I need to do. Login info was sent via signals
