### ISSUE TITLE
Staff -> Create -> Next -> Validation Improvements.

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#218]
@KPSbuttar If you fill out all the fields except the last ones and click submit, you'll see this:

![screen shot 2018-05-23 at 10 04 50 pm](https://user-images.githubusercontent.com/5767602/40460602-8cc803e8-5ed5-11e8-80a4-ae50699a1f23.png)

![screen shot 2018-05-23 at 10 05 02 pm](https://user-images.githubusercontent.com/5767602/40460606-92af1ab2-5ed5-11e8-80da-82d815ccd69b.png)

Can you make sure all the error text in the account type / password / etc get placed into the error box.

Thanks!

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir its fixed
