### ISSUE TITLE
Staff -> Update -> Validation

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#219]
Hi @KPSbuttar ,

Take a look:

![screen shot 2018-05-23 at 10 25 41 pm](https://user-images.githubusercontent.com/5767602/40461223-429ebdc2-5ed8-11e8-8e5e-c8970189f3ac.png)

As I write my password, the validation fields do not automatically change like in the other forms.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez All fixed
