### ISSUE TITLE
Large then small button

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#223]
Why is it when the page loads, this button starts off gigantic and then goes to the correct size?
![screen shot 2018-05-26 at 3 05 33 pm](https://user-images.githubusercontent.com/5767602/40579500-51963b14-60f6-11e8-9612-70f787163d24.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its done and fixed. 

Only reason for this @bartmika as you are using SVG and Path for the icons inside html page please don't use that instead only use Fontawesome icons.
Thanks
