### ISSUE TITLE
Province/Country NOT working for Add/Edit Staff, Member

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#226]
**Summary:**
At this URL
https://london.workery.ca/en/staff/create/

Cannot select a province or country from dropdown, but Staff members CAN be added

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir This is not UI issue, seems some api url to static folder issue. @bartmika sir in html console urls says unable to load static file can you please check.

**Comment by bartmika** [comment]
Hi @KPSbuttar,

I removed the ``json`` files and instead made the data accessibly through an API endpoints. I confirm the country fields get populated however now the province field do not get populated, it arrives blank. May you please investigate?

@rodolfomartinez FYI
