### ISSUE TITLE
Edit Client Button

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#234]
**Summary:**
Can we change the edit button (orange one) at pages like this
https://london.workery.ca/en/clients/summary/detail/23264/full/

to be the same as the one here (yellow with black text and different icon)
https://london.workery.ca/en/clients/summary/detail/23265/full/

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir for all screens. Please review all. Thanks.
