### ISSUE TITLE
Add Partner Screen - No Date Picker

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#237]
**Summary:**
At this URL
https://london.workery.ca/en/partners/create/
The date of birth field has a user icon with a small dropdown, and no date picker
<img width="899" alt="screen shot 2018-05-29 at 2 40 16 pm" src="https://user-images.githubusercontent.com/7537946/40678318-3c209f04-634e-11e8-8014-6e0e7b8497ec.png">

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir, Its done
