### ISSUE TITLE
Whitespace in your code editor

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#241]
Hi @KPSbuttar ,

On your machine, may you please update your code editor to use Linux/MacOS whitespaces and not Windows? The reason why when I get your code, the following issue happens. Take a look at the screenshot.

![screen shot 2018-05-29 at 6 32 38 pm](https://user-images.githubusercontent.com/5767602/40689128-dd3ccf28-636e-11e8-80d4-f80502614c21.png)

When you've fixed this issue on your side, close this ticket.

Thanks!

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir its done and will affect in all my future codes submissions and existing codes i guess are already reformatted. Thanks
