### ISSUE TITLE
Add Job -> Step 4 -> Add Blank Validation

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#242]
@KPSbuttar Hi Kanwar,

In this screen, can you add validation code which forces the user to select both entries before allowing the user to click next. FYI @rodolfomartinez 

![screen shot 2018-05-29 at 8 00 11 pm](https://user-images.githubusercontent.com/5767602/40691647-08d38328-637b-11e8-8a3d-c263ca4c9906.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its done sir. still need to check if it works fine after you refresh server. Please redeploy soon. thanks

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Ok sir i have reviewed its DONE. Thanks
