### ISSUE TITLE
Cannot Cancel Job?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#245]
**Summary:**
When trying to cancel a job and confirm this happens.  Basically, it is applying the validation that would apply to a successfully completed job.
![27a8874c-0b92-4792-bd7b-def2820ae1be](https://user-images.githubusercontent.com/7537946/40727315-a0dd7ea6-63f5-11e8-8e92-75c3891109ed.png)

**Comment by rodolfomartinez** [comment]
verified that this issue still exists in prod

**Comment by bartmika** [comment]
@rodolfomartinez Confirmed this is a bug on the backend - issue fixed.
