### ISSUE TITLE
Red Validation Box Missing?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#247]
**Summary:**
When cancelling a job at this URL
https://london.workery.ca/en/jobs/summary/detail/23948/close/

the validation appears for all fields as generic text. Not sure if this is an error or if the red box validation at the top is missing. if this is an issue please assign to @KPSbuttar

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its completed.
