### ISSUE TITLE
Redirect when using Add New Client during Add Job

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#249]
**Summary:**
When adding a job for a new client, it would be nice if we didn't launch the add customer in a new window, but rather added it in the same browser window, and upon successfully adding a customer, they are selected and we continue with the add job process.  If the customer is not added, the job creation process should be cancelled.

**Comment by bartmika** [comment]
Notes:
* Open in same browser
* Figure out how to handle breadcrumbs.
