### ISSUE TITLE
Password Validation UI

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#25]
**Summary:**
NOTE: Passwords should be at minimum 8 characters

When adding a password, it would be nice it the rules could be checked off as they are satisfied - for example, have a green checkmark appear when I have at least one upper case letter etc.

**Comment by bartmika** [comment]
Hi @KPSbuttar,

To modify any GUI in this project, you can go to the following directory root and look in here: https://github.com/over55/overfiftyfive-django/tree/master/overfiftyfive/templates

**Comment by rodolfomartinez** [comment]
Hi Kanwar, this could function similar ro this (but obviously we need it to look better)
https://www.w3schools.com/howto/howto_js_password_validation.asp

and could be applied to URLs like
http://london.o55.me/en/teams/create/

(scroll down to the bottom to the password section)

**Comment by rodolfomartinez** [comment]
@KPSbuttar please remember that @bartmika changed password structure so that minimum is now 8 characters

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir, finally this is completed for all forms as you can see. PLEASE Refresh server and make sure **base.css** file also gets refreshed  to make all password changes take effect.
Thanks!
