### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#258]
**Summary:**
At this URL https://london.workery.ca/en/jobs/create/step-6/
Can the modal in the picture below have the Yes button be green, and the No button be red

![92681c4f-090a-435d-828f-a63a7c71170f](https://user-images.githubusercontent.com/7537946/40895710-eec6bef2-677e-11e8-9f4c-1ef44a64c8f7.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done
