### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#260]
**Summary:**
At this URL
https://london.workery.ca/en/members/search/detail/6102/edit/
The error message is unclear. How can I edit this text?
![1b17a9fb-35f2-4535-aa5a-19ab472f705d](https://user-images.githubusercontent.com/7537946/40895845-a9806130-677f-11e8-8a31-e77137f9b2be.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir.

**Comment by KPSbuttar** [comment]
@rodolfomartinez  Added same Error message as you wanted here #229  Thanks
