### ISSUE TITLE
Edit Member - Province Dropdown Blank

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#261]
**Summary:**
This dropdown is blank again
https://london.workery.ca/en/members/search/detail/6102/edit/
![d4685ca2-f6bf-4ef1-b199-ba23a0996cda](https://user-images.githubusercontent.com/7537946/40895900-e5f8175c-677f-11e8-9931-a3dc06a2e77a.png)

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, I've taken a look into this and the provinces field works in other fields and it just breaks in the 'update' page for the associate. The problem appears to be jQuery as there are no errors in the static and api endpoints.

@KPSbuttar May you please take a look at the jQuery code?

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika It seems working now sir, please review. Thanks
