### ISSUE TITLE
Change Button Colour on Job Summary Screen

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#263]
**Summary:**
At the bottom of this URL

We need to change the colour of the four buttons on the bottom.

1: The begin button should be green

2: for the first button on the second row, change text to "Unassign Associate", make the colour yellow 

3: Make the "Close Job" button orange

4: Make the Postpone Job button Blue

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir this is done, All 3 buttons modified but i didn't find BEGIN button can you please share screen or share url where begin button need to edit. thanks

**Comment by rodolfomartinez** [comment]
@KPSbuttar - at this URL 
https://london.workery.ca/en/jobs/summary/detail/24078/lite/?page=1
when I click "48 Hour Follow Up"
I get to this URL
https://london.workery.ca/en/pending-tasks/28/

On this screen this Begin Job button should be "Green"
![a33b441d-ee52-4fda-83ba-cc46e1464f39](https://user-images.githubusercontent.com/7537946/41197657-30c60a7e-6c34-11e8-8bfb-734062648d5f.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir!
