### ISSUE TITLE
Total not calculating?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#264]
**Summary:**
At this URL
https://london.workery.ca/en/jobs/task/detail/24070/close/?task_id=2

Total is not calculating
![8917a9b7-2474-4954-8190-4b7c60ab47e8](https://user-images.githubusercontent.com/7537946/40896141-642234ea-6781-11e8-9151-f5d7b9436620.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its fixed.
