### ISSUE TITLE
Style Image Upload Button

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#267]
**Summary:**
At screens like this
https://london.workery.ca/en/members/summary/detail/6102/lite/?page=1
Where the image upload has been implemented, change the button to a bootstrap style button, make it blue with an image upload icon, and relabel the button to "Upload" and remove the "no files selected" text beside it. Also, if possible make the image upload animation a bit smaller, as it currently looks blurry
![81fc7386-b3d7-4a31-9079-f2fd7bc54d20](https://user-images.githubusercontent.com/7537946/40952769-a2bbbaf4-684a-11e8-8a5a-335adc9dea93.png)

**Comment by rodolfomartinez** [comment]
@KPSbuttar - status?

**Comment by rodolfomartinez** [comment]
@KPSbuttar - can we make it work like example 2 at this URL instead?
http://plugins.krajee.com/file-avatar-upload-demo

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir its done you can review all now. Thanks
