### ISSUE TITLE
Cannot Edit Job

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#268]
**Summary:**
Tried to edit this job and the system just scrolls back to top - no validation errors or confirmation; added a tag and hit update and nothing happened

@bartmika - please confirm who should be handling this issue

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir for this issue all jquery and UI work is done, basically my part is done and don't know if for all required fields API validations have already added by @bartmika sir. Lets review Thanks

**Comment by KPSbuttar** [comment]
Update_job_api validation work needs to do sir i guess @bartmika
