### ISSUE TITLE
Wrong login credentials validation

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#270]
**Summary:**
When trying to log in with an incorrect set of credentials, there is a modal that says "Wrong login credentials"

Can we change this to use our standard validation? If the email is incorrect please change to 
"This E-Mail address is not registered"

If password is incorrect,
"Incorrect Pasword"

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its UI is done can you please update API validation to get separate ERROR responses for both email and password. Thanks

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, I will implement this but your suggestion opens up a vulnerability in a system. A bot can now scan through the emails and find out user emails and then attempt to crack the passwords. This is why I obfuscated the original error message.

**Comment by bartmika** [comment]
Implemented with the messages you suggested.
