### ISSUE TITLE
Password Reset/System Emails down?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#272]
**Summary:**
Please confirm email service for workery.ca - cannot reset passwords

**Comment by bartmika** [comment]
Oddily enough I got emailing working on my local machine but not on production machine? I'll investigate.

**Comment by rodolfomartinez** [comment]
is this related to the switch from o55.me to workery.ca?

**Comment by bartmika** [comment]
@rodolfomartinez Nope, something to do with the emailer configuration. It appears we never setup an email account with [mailgun.com](https://mailgun.com) for ``workery.ca``. We are currently using the ``mikasoftware.com`` domain emailer for testing.

**Comment by rodolfomartinez** [comment]
Will create account now

**Comment by bartmika** [comment]
I confirm the reset password now works. I'll close this issue and we'll setup the password reset emailer for the ``workery.ca`` emailer.

**Comment by rodolfomartinez** [comment]
Sent
