### ISSUE TITLE
Cannot Update Financial Details for Job

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#274]
**Summary:**
At this URL
https://london.workery.ca/en/financials/unpaid-jobs/detail/24073/edit

Cannot successfully submit details for job.

@bartmika can you confirm if this is an issue for you or kanwar?

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir ALL UI work is done for this screen now @bartmika sir needs to look at api coding. Thanks

**Comment by bartmika** [comment]
Issue fixed.
