### ISSUE TITLE
Province field blank for update member

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#280]
**Summary** 
This dropdown is still blank but we ae still able to modify users

**Comment by bartmika** [comment]
The API endpoint has been implemented a few weeks ago which managed to resolve this GUI. It appears that this page needs to be updated. @KPSbuttar May you please investigate this?

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its done sir but make sure default province and country values should be 'ON' and 'CA' respectively as we added all correct validations and functions in member create form but don;t know how all members got wrong values like 'On' , 'Canada' etc which make select dropdowns not work. I hope you getting my point. OR @bartmika as i m seeing you have added API all validations for member create functions but for update API function only few are added you can fix that as well any way you want. thanks
