### ISSUE TITLE
Delete tag modal UI not working on Safari for iPad?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#281]
**Summary**
on iPad using Safari, when I try to delete a service fee tag my screen goes dark and no modal appears
https://london.workery.ca/en/settings/order_service_fees/

![d9c80b6c-b85d-4766-944e-e2407bbe6955](https://user-images.githubusercontent.com/7537946/41284247-b7000da0-6e06-11e8-9e11-094bbde34948.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir its done
