### ISSUE TITLE
Password reset UI

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#283]
**Summary:**
When using the password reset and inputting a nonregistered email, validation looks different than the rest of the system - generic modal instead of alerts
![screen shot 2018-06-12 at 6 31 39 am](https://user-images.githubusercontent.com/7537946/41285532-77d05b54-6e0a-11e8-9069-5123417bcdc6.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done. Added same error box here like login screen. Thanks
