### ISSUE TITLE
Password Reset Has no validation

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#284]
Hi Kanwar, can you try reset password and go to the change password page? There is no validation for this page, please implement. Here is a picture.

![screen shot 2018-06-12 at 7 48 31 pm](https://user-images.githubusercontent.com/5767602/41322936-a710f9ae-6e79-11e8-89c1-9eea67d06f45.png)

@rodolfomartinez FYI.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir its done.

**Comment by KPSbuttar** [comment]
@bartmika Hi sir Its done validations are fixed for this page but API validation needs to check can you please fix API errors for this page @bartmika sir! Thanks.

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, the current API endpoint is good enough so there is no need for another API endpoint. Can you try again?

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir its finally completed and all password functionality added. All done. Thanks!
