### ISSUE TITLE
Close Button Wrong Colour

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#287]
**Summary:**
At this URL
https://london.workery.ca/en/pending-tasks/15/

The "Close Job" button needs to be red and NOT green.

![screen shot 2018-06-15 at 9 13 41 pm](https://user-images.githubusercontent.com/7537946/41494450-1a565fe4-70e1-11e8-97bc-4b02a3f3f692.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir!
