### ISSUE TITLE
Province dropdown blank for edit member

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#288]
**Summary:**
The province dropdown is blank again for "edit member"

**Comment by bartmika** [comment]
Any GUI of this nature is @KPSbuttar issue as he implemented this.

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir their is no error in UI for this page actually as i mentioned in previous similar ticket that its Country and Province select dropdown option values which for some members comes as "Canada" "Ontario" which is wrong as json files to load so option value should be "CA" , "ON" and options labels will be Canada, Ontario which will load automatically loads. I hope you getting my point @rodolfomartinez so sir please make default values as CA ON not canada full text etc.
thanks

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Have fixed default country/region options to CA/ON Thanks

**Comment by rodolfomartinez** [comment]
@KPSbuttar - this is still happening
https://london.workery.ca/en/members/search/detail/6071/full/?was_modified=True

**Comment by KPSbuttar** [comment]
Hi sir @rodolfomartinez I can't see any issue here, its working perfectly here can you please recheck. thanks
