### ISSUE TITLE
Process to close a job is confusing

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#289]
**Summary:**

When the user first click to close a job, the UI is confusing and doesn't make it easy to distinguish between a successful completion and a cancellation. At a URL like
https://london.workery.ca/en/jobs/task/detail/24216/close/?task_id=2

Can we add a screen with a radio button in between with the following text:
Was this job successfully completed by the Associate?

The radio options should be 
Yes/No

This page should have a Back/Next button along the bottom.

If the user selects "No", then the next screen can take them down the cancacellation path, where they choose a reason.

If "yes", take them down the sucess path.

**Comment by bartmika** [comment]
@rodolfomartinez I'll have to push back on the Back/Next button and screen as I can place everything on a single screen.

I possible will be able to show you something tomorrow as I don't have time to deploy tonight.
