### ISSUE TITLE
Make customer feedback when closing a job optional

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#299]
**Summary:**
At URLs like 
https://london.workery.ca/en/jobs/task/detail/24105/close/?task_id=178

Can we make these questions (as well as the "Additional Comments" box at the bottom) optional?

**Was the quality of the work satisfactory? **
Yes
No
**Was the work completed on time and on budget? **
Yes
No
**Was the Associate Member punctual? **
Yes
No
**Was the Associate Member professional? **
Yes
No
**Would you refer Over55 to a friend of family member? **
Yes
No

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir. So only 1st Reason field is REQUIRED that is not optional is that ok ?
