### ISSUE TITLE
7 Day Follow up Task - Summary Table

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#302]
**Summary:**
These changes should ONLY apply to a 7 day follow up task, such as the one at this URL
https://london.workery.ca/en/pending-tasks/178/

1. Summary Table title should be adjusted as per #301 
2. Row 2 (Task 7 Day Follow up) can be hidden from the UI
3. Row 6 (Last modified at) can be hidden from UI
4. Row 7 (Last modified by) can be hidden from UI
5. NEW Row 6: this should be "Client Name"
6. NEW Row 7: this should be "Client Phone Number"
7. NEW Row 8: this should be "Associate Name"

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir Its done. So all changes are done and for NEW Rows UI is done and that Django dynamic values will be added by @bartmika sir. Thanks

**Comment by rodolfomartinez** [comment]
@bartmika can you please have a look so the tables can be populated?
