### ISSUE TITLE
7 Day follow up (Completion Survey) Task Screen - Success Path

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#304]
**Summary:**
If at this URL
https://london.workery.ca/en/jobs/task/detail/24105/close/?task_id=178

we need to insert a summary table (similar to the summaries for tasks, etc.) with the following items at the TOP of the page

Column 1                      Column 2
Customer Name          customer name
Associate Name          associate name
Job Description        job description

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir. Ui table is added as desired and Table dynamic django values will be added by @bartmika sir i guess. thanks

**Comment by rodolfomartinez** [comment]
@bartmika can you please have a look to populate tables?
