### ISSUE TITLE
Task Summary - 48 Hour Follow Up

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#306]
**Summary:**
These changes should ONLY apply to a 48 hour follow up task, such as the one at this URL
https://london.workery.ca/en/pending-tasks/187/?page=2

Summary Table title should be adjusted as per #301
Row 2 (Task 48 hour follow up) can be hidden from the UI
Row 6 (Last modified at) can be hidden from UI
Row 7 (Last modified by) can be hidden from UI
NEW Row 6: this should be "Client Name"
NEW Row 7: this should be "Client Phone Number"
NEW Row 8: this should be "Associate Name"

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done.

**Comment by rodolfomartinez** [comment]
Still looks the same to me
Screenshot:
![041771f4-97ae-436e-a2c4-cff12db93f77](https://user-images.githubusercontent.com/7537946/41874928-543d5ed4-7897-11e8-8435-bca173323593.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done

**Comment by rodolfomartinez** [comment]
@bartmika - can you please add the necessary code to populate thist able?
