### ISSUE TITLE
48 hour follow up - Task Summary Table

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#307]
**Summary:**
These changes should ONLY apply to a 48 hour follow up task, such as the one at this URL
https://london.workery.ca/en/pending-tasks/187/complete/

we need to insert a summary table (similar to the summaries for tasks, etc.) with the following items at the TOP of the page

Column 1 Column 2
Customer Name       customer name
Associate Name       associate name
Job Description       job description

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done.
