### ISSUE TITLE
Summary Table - Assign Associate

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#310]
**Summary:**
These changes should ONLY apply to the "Assign Associate" task, such as the one at this URL
https://london.workery.ca/en/pending-tasks/208/

Summary Table title should be adjusted as per #301
Row 2 (Task 48 hour follow up) can be hidden from the UI
Row 6 (Last modified at) can be hidden from UI
Row 7 (Last modified by) can be hidden from UI
NEW Row 6: this should be "Client Name"
NEW Row 7: this should be "Client Phone Number"
NEW Row 8: this should be "Job Description"

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its completed
