### ISSUE TITLE
Changing text for reports details page

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#323]
**Summary:**
At URLs like this
https://london.workery.ca/en/report/12/

How can I change the text?

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir this is the para where you add text https://github.com/over55/workery-django/blob/e96b14f9c25b8aa333ce1faaece2717d1a7b5e98/workery/templates/tenant_report/report_14_view.html#L77

Plus 
This directory shows all reports files https://github.com/over55/workery-django/tree/master/workery/templates/tenant_report

**Comment by KPSbuttar** [comment]
@rodolfomartinez This is UI and static text additions but @bartmika Sir can you suggest file which dynamic changes this??

thanks
