### ISSUE TITLE
Pending State for job assignment

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#326]
**Summary:**
Currently, when assinging an Associate we can only choose if they accepted and Yes or No.  We would like a third state called "pending" which does not assign or commit the Associate, but at least we can track that we have offered it to them. On the job/task summary list, it should display the Associate name with (pending) in brackets. So for Associate Bart Mika, it would read
Bart Mika (pending)

**Comment by rodolfomartinez** [comment]
additional notes:
I would say we add a third option that says "Pending" and we would write in the comment box something to the effect of "Left message for associate".  There would be a 24 hour task called "Confirmation" and our staff would go in and change assign to either Yes or No

and the status for this would be Pending

because the scenario in the office is this: in an ideal world we woud always get a hold of an associate on the first try and they would tell us yes or no

the reality is that we often leave messages, and need to track that we did leave messages, ie a pending state because we dont know what the associate wants to do

**Comment by bartmika** [comment]
TODO: delete "has_accepted_job" field in `ActivitySheetItem` model.
