### ISSUE TITLE
Close out process (7 Day)

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#332]
**Summary:**
For this process, I asked Kanwar to make everything except reason optional, because sometimes we can't get a hold of the client. Need a way to indicate this without impacting the Associate's star rating. Let's discuss

**Comment by rodolfomartinez** [comment]
@bartmika - this is related to #333

**Comment by rodolfomartinez** [comment]
@bartmika my only remaining concern is that if we leave it blank it does not count yowards star rating

**Comment by bartmika** [comment]
I must implement:
- A radio button which controls whether survey was done or not
- Survey is hidden by default
- Survey becomes visible if "Yes" option was selected.
- Do not affect associate score if "No" option was selected.

**Comment by RaymondO55** [comment]
@bartmika Bump. Proceed with this when you find the time

**Comment by bartmika** [comment]
@RaymondO55 Confirmed! Please verify the job creation code works according to specification.
