### ISSUE TITLE
Star Ratings not calculating in UI?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#333]
**Summary:**
Star ratings do not appear to be calculating.

Also, I asked Kanwar to make customer feedback questions optional because we cant always get a hold of customers, so if the questions are blank they should not enter the calculation (i.e. they should not be a 5 or 0 against the average, but rather just a null or never happened)

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, I've added the dynamic value for the score, you can use this value to fix this issue. Please look here to see that value - https://github.com/over55/workery-django/blob/c96a474bc7574236bd13eae3440b83902110f43b/workery/templates/tenant_associate/retrieve/lite_view.html#L52

@rodolfomartinez FYI.

**Comment by bartmika** [comment]
Hi @KPSbuttar, what is the status of this issue? @rodolfomartinez

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its done sir can you send me URL for some MEMBER Which has GIVEN RATING just need to check @bartmika sir!!

Thanks
