### ISSUE TITLE
Cannot add user?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#334]
**Summary:**
I tried to add a new user
rachel@o55.ca

and received an error that email is not unique, but we have no staff or users with this email

Please investigate

**Comment by bartmika** [comment]
That email is not unique, in fact it already exists ... https://london.workery.ca/en/staff/list/detail/15/edit/ ... the problem is the "email" is not being displayed in some of the GUI. I will investigate what the problem is.

**Comment by bartmika** [comment]
Rachael does exist except she is under "list" section because her account is "inactive". I've fixed the GUI so you should see the emails now.
