### ISSUE TITLE
Cannot delete News Items/Announcements

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#335]
**Summary:**
Cannot delete news items/announcements

**Comment by bartmika** [comment]
This appears to be GUI related, I don't see any API calls. @KPSbuttar please investigate.

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir. So you can delete from here: https://london.workery.ca/en/settings/awaylogs/

But if you want me to add Delete button in Dashboard page as well under +ADD button will add that as well please comment. Thanks

**Comment by rodolfomartinez** [comment]
yes - please - but I don't want the UI to become cluttered, so just make it an X icon in a red square

**Comment by KPSbuttar** [comment]
@rodolfomartinez Dasboard ui is done please check and for the delete cross to functions @bartmika sir can you create django api function for delete here delete_away_log_api() like this. Just added cloned function. Thanks

**Comment by bartmika** [comment]
@KPSbuttar Thank you Kanwar, I've implemented - @rodolfomartinez issue fixed.
