### ISSUE TITLE
Job gives 500

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#336]
**Summary:**
This job gives a 500
https://london.workery.ca/en/pending-tasks/293/

These are the only notes I have from my staff
This job is a housekeeping job that was assigned to Kathrine, but she declined after visiting and finding out client Todd is a smoker. I unassigned Kathrine (before the system was updated) and now the task and job order is broken.

**Comment by bartmika** [comment]
Where is the Job in the https://london.workery.ca/en/pending-tasks/ page? I cannot match the ID "293" to the data listed.

**Comment by bartmika** [comment]
Bug confirmed and fixed.
