### ISSUE TITLE
Org Time Zone Setting

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#339]
**Summary:**
In the future, could be add a settings for the org profile where we could set the time zone, and perhaps other items? Let's discuss.

**Comment by bartmika** [comment]
Currently we do support different timezones. We just need to create GUI which supports updating the Tenant Franchise with our timezone options to choose from.

**Comment by bartmika** [comment]
The creation process also has timezone selection. We have full support for different timezones! 👍

**Comment by bartmika** [comment]
Also I would like to note that the database core uses `UTC` format for saving but when we retrieve the data then it's formatted according to the franchise timezone, in this case we have `American/Toronto`.
