### ISSUE TITLE
Cannot make staff active

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#340]
**Summary:**
When editing a user in safari on macOS, I cannot make a staff member active. I hit submit and nothing happens.
https://london.workery.ca/en/staff/list/detail/17/edit/

**Comment by bartmika** [comment]
Solution: 
(1) Lookup user to see if they exist for email
(2) if user does not exist (DNE) then create new user
(3) attach user to staff
(4) problem fixed
