### ISSUE TITLE
Due date disappeared from Tasks view?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#342]
**Summary:**
The Due date column is now blank on the Task list screen
https://london.workery.ca/en/pending-tasks/

is this related to UTC or a UI issue?

**Comment by rodolfomartinez** [comment]
@KPSbuttar - please review to see if this is a UI issue

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its fixed sir and yes it was Django issue template tags like `{{ task_item.due_date|timezone:request.tenant.timezone_name }}` was not working so i updated as `{{ task_item.due_date }}` this worked. @bartmika sir can you please look at timezone issue. Thanks.

**Comment by bartmika** [comment]
@rodolfomartinez Couldn't find any.
