### ISSUE TITLE
Favicon.ico and other branded icons

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#344]
We will need branded icons for the site. 

Use tools to help you out like https://www.favicon-generator.org

**Comment by bartmika** [comment]
@rodolfomartinez 
Please provide the following image files:

* 16x16
* 32x32
* 57x57
* 60x60
* 72x72
* 76x76
* 96x96
* 114x114
* 120x120
* 144x144
* 152x152
* 180x180
* 192x192

If you find any more, feel free to add them, here an interesting article to help https://stackoverflow.com/questions/2268204/favicon-dimensions

**Comment by rodolfomartinez** [comment]
emailed to you @bartmika
