### ISSUE TITLE
Console error?

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#345]
![screen shot 2018-06-27 at 7 19 03 pm](https://user-images.githubusercontent.com/5767602/42004704-0230c56e-7a3f-11e8-8323-16778444dadc.png)

**Comment by bartmika** [comment]
@rodolfomartinez Do you see any errors in your browser console?

**Comment by KPSbuttar** [comment]
@rodolfomartinez  @bartmika No sir i cant't see any in my browser console. Can you please share any specific page which showing these errors.

**Comment by bartmika** [comment]
@rodolfomartinez Can you confirm in your work machine and your home machine to confirm you get no errors in the console for all your browsers?

**Comment by rodolfomartinez** [comment]
I cant find any w safari or chrome
