### ISSUE TITLE
Service Fee Calculation

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#348]
**Summary:**
At URLs like this
https://london.workery.ca/en/financials/unpaid-jobs/detail/24088/edit
total service fee = total about amount x %value from dropdown

materials should NOT be included in this calculation

**Comment by rodolfomartinez** [comment]
@KPSbuttar - can you please solve this

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its fixed

**Comment by rodolfomartinez** [comment]
If a user enters an amount for tax, it should be EXCLUDED from the service fee calculation. Currently is is INCLUDED.

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its fixed.
