### ISSUE TITLE
Completed and paid jobs not being moved out of unpaid

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#349]
**Summary:**
At URLs like
https://london.workery.ca/en/financials/unpaid-jobs/detail/24154/?page=1

This job has been completed and paid, but is still under the complete but unpaid count. I believe the system has correctly classified it as "completed and paid" (you can verify agains thte status), but it is still on the list under Financials > Unpaid

**Comment by bartmika** [comment]
Code now works.
