### ISSUE TITLE
No confirmation when adding client

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#364]
**Summary:**
This may be a UI issue for @KPSbuttar - when adding a new client, there confirmation modal is gone, and hitting the Add button does not advance the screen, but it does create the client in the background, so if the user hits the button multiple times, several duplicates of the same client are created

**Comment by rodolfomartinez** [comment]
@kpsbuttar please fix:
Backend error says that country was not specified, can you get Kanwar to check the front end code ? If he confirms country code is being entered in the GUI then it's a backend problem.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir its not an UI issues i tried at the backend editing py files but seems will be resolved by @bartmika sir. Found no UI or Jquery issues its just the api is not calling password etc validation in details form.
Moreover for confirmation modal with message "Client Successfully created." UI is already there at clients summary dashboard. If its not get display after creation must be issue with this "`parameters.was_created`" not getting true may be @bartmika lease check.

Thanks
