### ISSUE TITLE
24 hour follow up task

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#370]
**Summary:**
Accepting the 24 hour follow up skips the 48 hour follow up, and goes straight to the 7 Day

**Comment by bartmika** [comment]
@rodolfomartinez  Do you recall what steps you took to reproduce this problem? Or does this happens with all entries?

**Comment by bartmika** [comment]
I just checked on my local machine and I cannot replicate? Do you know what I am doing wrong?

**Comment by rodolfomartinez** [comment]
OK steps that I just took with Job 24338
1. Created a new job for client Rodolfo Martinez
2. Assigned Associate patricia Castro with a "Pending" option
3. Entered the 24hr follow up task
4. Selected that Patricia has accepted.
5. This job is now marked complete but unpaid

The workflow should be:
1. Pending creates a 24hr follow up.
2. Accepting at 24 hour follow up creates a 48 hour follow up to confirm that client and associate will  meet - in this case, proceed to 3. Declining changes status to declined, and a new associate must be assigned - in this case proceed back to 1.
3. If accepted, and client and associate will meet (ie NOT cancelled at this point), then proceed to 5. If client and associate will not meet, (ie job cancelled before they meet) proceed to 4.
4. The user would "close" the job as unsuccessful
5. Create 7 day follow up task.
6. After completion of task move to complete but unpaid
7. mark as paid in financials

**Comment by bartmika** [comment]
Hi Rodolfo, on my local machine I ran something similar to what you wrote however it worked as the workflow you specified and not what you observed.
