### ISSUE TITLE
Set default role to "Frontline"

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#377]
**Summary;**
When creating a new user, the role field is blank and has no validation, allowing us to create staff with no roles, and unless if edited they can do nothing.

Can we set the UI so that it cannot be blank and by default frontline is selected? If this is an issue for @KPSbuttar please re-assign

**Comment by bartmika** [comment]
@rodolfomartinez Will do!

**Comment by bartmika** [comment]
@rodolfomartinez  Technically there should be validation on the server to prevent this error submission - once implemented I'll have to re-assign to Kanwar to update the GUI.

**Comment by bartmika** [comment]
@rodolfomartinez Fixed and no need to assign Kanwar.
