### ISSUE TITLE
Associate Fees Due

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#388]
**Summary:**
Associate’s Jobs:
It would be advantageous to have a report based on the ASSOCIATE, what jobs are outstanding, not completed and not paid and paid
Therefore when an Associate comes into the office to pay for their work, we can quickly pull up a report of the outstanding jobs – etc
         Select Associate, Date, completed date range, - listing all jobs (new, completed, paid, etc)
​Job #, Clients Name, skill set, labour $, inv #,
This could be broken into two reports – 1)  unpaid and 2) paid
Or just one report and we can sift thru the data……????  (HOWEVER if we had a preference, two reports)
Associates Job – unpaid
Associates Jobs – paid

**Comment by rodolfomartinez** [comment]
@bartmika - was this clarified by @SusanFaiarley

**Comment by bartmika** [comment]
@RaymondO55 @rodolfomartinez Please provide me more details and re-assign back to me.

**Comment by RaymondO55** [comment]
@bartmika Susan clarified. For the "Fees Due" report she wants the jobs to be tracked by their Assignment Date and she also wants the Assignment Date added into the report. This should also be clarified in the initial date range screen. Image provided for clarification
![service fees](https://user-images.githubusercontent.com/41381131/43274256-af318ff2-90cc-11e8-8648-435c0b1953e1.png)

**Comment by bartmika** [comment]
@RaymondO55 Confirmed! I will implement accordingly.

**Comment by bartmika** [comment]
@rodolfomartinez 
> It would be advantageous to have a report based on the ASSOCIATE, what jobs are outstanding, not completed and not paid and paid

Add the filter in this report to filter by either (1) paid or (2) unpaid jobs or (3) both paid/unpaid.


> Therefore when an Associate comes into the office to pay for their work, we can quickly pull up a report of the outstanding jobs – etc

Skipped - This needs to be in a different report.

> Select Associate, Date, completed date range, - listing all jobs (new, completed, paid, etc)

Skipped - This needs to be in a different report.

> ​Job #, Clients Name, skill set, labour $, inv #,

Added the due fee, the invoice number, and labour/material costs.

> This could be broken into two reports – 1) unpaid and 2) paid

No need, this report will handle it.

> Or just one report and we can sift thru the data……???? (HOWEVER if we had a preference, two reports)
Associates Job – unpaid
Associates Jobs – paid

**Comment by bartmika** [comment]
@RaymondO55 May you please QA and confirm this report is acceptable? Please assign back to me any modifications you would like or else close ticket if it's acceptable to close. Thanks! 

@rodolfomartinez Please review as well.

**Comment by bartmika** [comment]
@rodolfomartinez Please checkout the new report I created for individual associates. https://london.workery.ca/en/report/15/

@RaymondO55 FYI

**Comment by rodolfomartinez** [comment]
@bartmika @RaymondO55 - I believe this has been superseded by more recent tickets. Please create a new ticket if this is NOT the case.
