### ISSUE TITLE
Activity Sheet - Hide ID# near bottom

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#392]
**Summary:**
At URLs like these
https://london.workery.ca/en/pending-tasks/690/activity-sheet/

near the bottom can we please hide the ID# column

![e2f0e1b8-9af2-4953-b9a4-085df4213943](https://user-images.githubusercontent.com/7537946/42726574-a5364e96-8764-11e8-945d-debf4a45f71d.png)

**Comment by bartmika** [comment]
Hi Rodolfo, I added these IDs in to help debug issues. I can remove them.
