### ISSUE TITLE
Add buttons to filter job types for member

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#395]
**Summary:**
**For Job Page (for associate)**:
https://london.workery.ca/en/members/summary/detail/6088/jobs/

At this URL, where can we add buttons for the following under the "Jobs" titles

In Progress
Paid
Unpaid
Declined
All jobs 
![37cdb557-ed5d-4aa3-892d-e06dec2604ea](https://user-images.githubusercontent.com/7537946/42783066-c9c60034-8918-11e8-99ae-1b6cc33e65f6.jpeg)

**Comment by rodolfomartinez** [comment]
@kpsbuttar could this be a dropdown instead since there are already so many buttons? Or some kind of filter UI? Please show some examples before implementing

**Comment by bartmika** [comment]
@rodolfomartinez I will put in GUI which works, it may not be good GUI but @KPSbuttar can modify according to your direction.

**Comment by bartmika** [comment]
@rodolfomartinez Finished - may you please check?

**Comment by rodolfomartinez** [comment]
have discussed with @KPSbuttar - he will implement a dropdown to avoid confusion with other buttons and UI clutter

**Comment by rodolfomartinez** [comment]
@KPSbuttar - bump

**Comment by KPSbuttar** [comment]
@rodolfomartinez  @bartmika Hi sir, this is completed please review all. Thanks
