### ISSUE TITLE
Advanced Search - add Address Line

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#397]
**Summary:**
Can we add an address line to advanced search after Last Name field

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, to let you know the backend filtering for this has been implemented, simply use ``street_address`` field to filter by. I'll give two examples to help you.

### Example 1
Lets say you want to find all the address which contain the text **120**, then you would search like this:

``
https://london.workery.ca/en/clients/search/results/?street_address=120
``

### Example 2
Lets say I want to find all address containing something like **120 Centre Street** then you would search like this (notice you must replace the whitespace characters with the plus symbol):

``
https://london.workery.ca/en/clients/search/results/?street_address=120+Centre+Street
``

**Comment by rodolfomartinez** [comment]
@KPSbuttar - please resolve

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika This is COMPLETED sir, Please review all. Thanks
