### ISSUE TITLE
Client Blacklist Function

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#398]
**Summary:**
We need to implement a "blacklist" function for problematic clients

**Comment by rodolfomartinez** [comment]
I would like something where when we edit a client there is an option similar to the active question which says “Blacklist” only available to managers

**Comment by RaymondO55** [comment]
@bartmika Blacklisting works as you designed it but we would like to include additional functions using it.
We would like to make it so they are unable to be given a job. The following changes should be implemented:
![blacklist selection](https://user-images.githubusercontent.com/41381131/43531864-c4db0264-957e-11e8-9ed1-2747754e4d29.png)
During job creation, selection of the client should have clear indication that the client is blacklisted and the select button should be unavailable
