### ISSUE TITLE
Hide "Back buttons"

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#403]
**Summary:**
Can we hide the "Back" (e.g. "Back to member's Home") button from the UI>?

**Comment by bartmika** [comment]
@rodolfomartinez Sure thing, that would simplify all the pages - make them less cluttered. How should we proceed?

**Comment by rodolfomartinez** [comment]
Let's hide them

**Comment by bartmika** [comment]
@rodolfomartinez Confirmed, I will remove all top "Back to X" buttons on top of each page.

**Comment by rodolfomartinez** [comment]
closed.
