### ISSUE TITLE
Job Summary Table

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#405]
**Summary:**
At URLs like these
https://london.workery.ca/en/jobs/summary/detail/24420/lite/?page=1

Please make the following changes:
1. Remove the "Back to Jobs Home" button 
2. Remove the "Job Summary" title above the table (as per picture below)
3. Change the Table Header Row/Title to be: Job #xyz - Summary
(where xyz is equal to the actual Job #)
So instead of the table header row (in black) reading "Summary Details"
URL https://london.workery.ca/en/jobs/summary/detail/24420/lite/?page=1
would have a table header row reading:
Job #24,420 - Summary

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its completed sir!
