### ISSUE TITLE
Table Header Style

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#407]
**Summary:**
At URLs like this
https://london.workery.ca/en/clients/summary/detail/23472/full/
Please make table headers the same shade of black as the ones here
https://london.workery.ca/en/jobs/list/detail/24424/lite/?page=1

instead of the current blue

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir, its done if any Table is left please share link in this ticket will do. Thanks
