### ISSUE TITLE
Stepped Progress UI Change

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#408]
**Summary:**
This should happen on the dev box first

We should replace the step/progress UI with this look:
![04002213-b946-4842-b160-9297b2f38c40](https://user-images.githubusercontent.com/7537946/42836396-eff0435e-89c8-11e8-8e7d-bf29e0ea4ea7.jpeg)

This would be implemented at this page
https://london.workery.ca/en/jobs/create/step-1/search-or-add
use the cyan blue color from the "back to top" arrow, and the steps should be:
1. Add Job
2.

**Comment by bartmika** [comment]
@rodolfomartinez @KPSbuttar What is the status of this issue?

**Comment by rodolfomartinez** [comment]
@KPSbuttar - please create an example on inthought.pw - DO NOT deploy to prod without approval from @bartmika

**Comment by rodolfomartinez** [comment]
@KPSbuttar - please remember - this can be your last ticket and DO NOT deploy to prod

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its done sir, PLEASe review this new UI here: http://inthought.pw/jobs/step_form.html#step-2

Please message if all ok so i can implement it over production site.
Thanks

**Comment by rodolfomartinez** [comment]
thoughts @bartmika ? I think we need to trim the labels, and on an phone in portrait orientation it is unreadable, but I like the initial concept

**Comment by bartmika** [comment]
@rodolfomartinez Love it. As long as we find a good solution for mobile, then I support moving forward with these as replacements.

**Comment by rodolfomartinez** [comment]
@KPSbuttar - this looks good so far. Are the steps clickable as nagivation? Also, can we do something about iPhone? I realize the display is small but if there is a fix for potrait mode than we can proceed with this

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, what is the status of this issue? Thanks!

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika This is done sir all UI for MOBILE screens are fixed and changes are done as you mentioned above. Please review here:

http://inthought.pw/jobs/step_form.html
http://inthought.pw/jobs/job_add.html
