### ISSUE TITLE
(2) Remove "Service Fee" from page

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#410]
Please remove the "service fee" from the "job creation" stage.

(The reasoning is that we can set the service fee in financials section)

**Comment by rodolfomartinez** [comment]
I know that this has been requested by frontline staff.  We should proceed

**Comment by bartmika** [comment]
@rodolfomartinez Please QA and then close when confirmed.

**Comment by rodolfomartinez** [comment]
Confirmed
