### ISSUE TITLE
(3) Merge address fields in tables

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#411]
For every page with a summary table that has address field - please merge them all into a single field called "location".

**Comment by rodolfomartinez** [comment]
So rather than 
Address: 1848 Mickleborough Drive
City: London

Location: 1848 Mickleborough Drive, London

?

**Comment by RaymondO55** [comment]
Not quite. Currently the summary has these lines
Address: 123 Existing Street
Address (Extra): 
City: London
Province: Ontario
Country: Canada
Postal Code: N6H 1B4
PO Box: N/A

I would like to get it compressed as follows:

Address: 123 Existing Street
Address (Extra): 
Location: London, Ontario, Canada

Postal Code and PO Box can be removed altogether as the information is unneeded and in the niche case that the information is required it can easily be accessed by accessing the clients file details.

**Comment by rodolfomartinez** [comment]
@RaymondO55 - please provide a sample URL and screen cap to clarify

Thanks

**Comment by rodolfomartinez** [comment]
At activity sheet URLs like these
https://london.workery.ca/en/pending-tasks/848/activity-sheet/

Please rename "Customer Address" to
Location
which will display {{{street address}}} {{{city}}} {{{province/state}}}

and remove the following fields

Customer Street Address (Extra)
Customer City
Customer Province
Customer Country
Customer Postal Code
Customer Post Office Box

**Comment by bartmika** [comment]
@rodolfomartinez Can you QA and close when verified?

**Comment by rodolfomartinez** [comment]
Looks good except for one details - the CA is confusing as this could be interpreted as either Canada or California. Can we either remove the two letter country code or change to "Canada"
