### ISSUE TITLE
(5) Go to task on job creation

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#413]
When a job gets created in from the last job creation step, please redirect the user to the task instead of the tasks landing page.

(Reasoning is staff has to go to pending tasks to find task to assign an associate)

**Comment by rodolfomartinez** [comment]
**Summary:**
This looks good to me

**Comment by bartmika** [comment]
@rodolfomartinez Please QA and then close when confirmed.

**Comment by rodolfomartinez** [comment]
Confirmed
