### ISSUE TITLE
(6) BUG: Some jobs missing "latest_pending_task"

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#414]
Investigate some jobs do not have a pending task in the summary table in the job lite view.

**Comment by rodolfomartinez** [comment]
**Summary:**
Please investigate

**Comment by bartmika** [comment]
@rodolfomartinez Please QA and then close when confirmed.

**Comment by rodolfomartinez** [comment]
@RaymondO55 - please review.
If this a good sample URL?
https://london.workery.ca/en/pending-tasks/471/?page=1

**Comment by bartmika** [comment]
Please note:
(1) This fix will only work on newly created jobs.
(2) Legacy or past jobs will be missing this if they where created and nothing was done with them.

**Comment by rodolfomartinez** [comment]
@RaymondO55 - please review
