### ISSUE TITLE
(8) Unassigned tasks

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#416]
(a) Unassigned tasks appear to look buggy

(b) Might be working now? It might just be old data messing it up?

(c) Unassigned are old tasks which have not been dealt with

**Comment by rodolfomartinez** [comment]
**Summary:**
I suspect this is related to legacy jobs. May be related to skillsets being accidentally deleted, which removed associates from legacy jobs, having them show up as "unassigned". We could edit these manually to correct

**Comment by rodolfomartinez** [comment]
@bartmika this appear to impact non legacy jobs. Need to investigate further.

**Comment by bartmika** [comment]
@rodolfomartinez The issue was found, it appears some we need to add a filter to check to see if a `Task` was not closed for the filter. I've added that code and it's beginning to look good to me.

**Comment by bartmika** [comment]
@rodolfomartinez May you please QA and close if you feel issue has been closed?

**Comment by rodolfomartinez** [comment]
@RaymondO55 - please review to see if this is working
