### ISSUE TITLE
(9) Pagination improvements

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#417]
Staff is scrolling all the way to the bottom to utilize pagination - they are unhappy with the extra scrolling. The fix is to have scrolling somewhere near top for connivance.

(a) Come up with a design that looks and feels good. Also must work for all our pages.

(b) Assign @KPSbuttar to apply this new pagination enhancement to all the pages.

**Comment by rodolfomartinez** [comment]
I feel like the UI may be overloaded as is near the top; not sure what the best fix is.

**Comment by bartmika** [comment]
@rodolfomartinez Can @KPSbuttar make some mock up prototypes, submit to this ticket screenshots and we pick the best design?

**Comment by bartmika** [comment]
@rodolfomartinez Understood, I'll leave this ticket in your name and you can decide how to proceed with this issue.

**Comment by bartmika** [comment]
![screen shot 2018-07-25 at 11 43 43 pm](https://user-images.githubusercontent.com/5767602/43240470-a2c7bd6c-9064-11e8-8b2b-fb05eefacd4d.png)

@rodolfomartinez Can I get a design from @KPSbuttar on how you expect this GUI to look? I got the backend to support pagination on every **list** page. So for example if type this you will get much more records then default:

``
https://london.workery.ca/en/clients/list/?paginate_by=250
``

Once I get a GUI design I will integrate the pagination system with the GUI.
