### ISSUE TITLE
(11) Pagination size

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#419]
Advanced staff users would like the ability to select how many items to paginate from in the GUI.

For example:
* by 25
* by 50
* by 100

Add ability for users to choose different sizes, but page loads by default to the current pagination size if user did not specify

**Comment by rodolfomartinez** [comment]
This sounds like an enhancement more than a bug, and I think we are adding more UI complexity. Perhaps a compromise would be to have an org setting where we set the pagination limit?
