### ISSUE TITLE
(13) Comments to task summary pages

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#421]
In all tasks summary tables for all pending detail pages which use summary tables, please do the following:

(a) Link to the job comments
(b) Have count of number of comments for that job
(c) Make counter vibrant - ex 1: Red pill with number or ex 2: notification in apps look
(d) Add most recent comment in the table.

**Comment by rodolfomartinez** [comment]
Agreed - we need to proceed with this item

**Comment by bartmika** [comment]
@rodolfomartinez Can we get @KPSbuttar to create a notification example for this GUI item on the template page? Currently we don't have any designs for it.

**Comment by bartmika** [comment]
@rodolfomartinez Closing job, you will need to create a separate ticket for the gui person to improve the GUI.
