### ISSUE TITLE
(16) Where is "reason" for cancelled?

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#424]
It appears we collect the reason the job was cancelled but we do not display the cancel reason in any of the job lite / full detail pages.

Please put the reason for cancelled under "Status" row.

**Comment by rodolfomartinez** [comment]
Can we add the reason in the Status row if the job is cancelled - I do not think we should crowd UI with another row. So an example:

Status: Pending

becomes cancelled, because quote was too high, so becomes

Status: Cancelled - Quote was too high

**Comment by bartmika** [comment]
@rodolfomartinez Great idea! Will implement.
