### ISSUE TITLE
(20) Ongoing issue

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#428]
Notes:

* Ongoing is not working for 055

* O55 wants to expand number of jobs.

Purposed Workflow:

* (a) Re-assign associate looks buggy

* (b) Remove automatic job creation

* (c) Recreate a task instead of a job at first of new month / close previous months task

* (d) When "Add job" clicked, if staff clicks "Ongoing" then only create master ongoing form and not job

* (e) Create assign associate to "master form" for ongoing job on create job.

* (f) When clicking "pending task" list and details, replace Job Order IDs with "master form" IDs.

* (g) All master forms create a "task" at end of month asking "how many visits in previous months

* choose zero to x

* if submit on x then create x number of jobs

* attach new jobs to the master form

* start/finsih date is set to first day of month

* all created jobs are cloned from master form

* all created jobs start as "completed but unpaid" and it is O55's responsibility to update in the financials section

(@rodolfomartinez please read and close, create a new ticket with the decision made by O55 team)

**Comment by RaymondO55** [comment]
The process is almost as I want it. Here are some revisions and clarifications for review.

- Start date should be set to the first day of the month

- Finish date takes whatever is entered as the "Invoice Date" during the job payment process

> "(c) Recreate a task instead of a job at first of new month / close previous months task"
   "(g) All master forms create a "task" at end of month asking "how many visits in previous months"

***IMPORTANT NOTICE***
This "Task" must only be available on Manager accounts. This process should only be handled by those who have permissions to handle financial data.

Please review and proceed with the implementation of this item as described in your original post with my revisions.

**Comment by bartmika** [comment]
@rodolfomartinez @RaymondO55 Understood! Implementing now.

**Comment by bartmika** [comment]
@RaymondO55 @rodolfomartinez 

> (a) Re-assign associate looks buggy

TODO - Investigate 


> (b) Remove automatic job creation

Done 


> ”(c) Recreate a task instead of a job at first of new month 

Done



> / close previous months task"

Skipped - It is up to O55 manager staff to close any previous tasks.


 > This "Task" must only be available on Manager [and executive] accounts. This process should only be handled by those who have permissions to handle financial data.

Done



> (d) When "Add job" clicked, if staff clicks "Ongoing" then only create master ongoing form and not job 
Done



> (e) Create assign associate to "master form" for ongoing job on create job. 
Done



> (f) When clicking "pending task" list and details, replace Job Order IDs with "master form" IDs. 
Done



> (g) All master forms create a "task" at end of month asking "how many visits in previous months > choose zero to x > if submit on x then create x number of jobs > attach new jobs to the master form > start/finsih date is set to first day of month > Start date should be set to the first day of the month > Finish date takes whatever is entered as the "Invoice Date" during the job payment process 
Done



> all created jobs are cloned from master form 
Done 



> all created jobs start as "completed but unpaid" and it is O55's responsibility to update in the financials section

Done
