### ISSUE TITLE
(22) Ability to change "Residential" customer to "Commercial" customer

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#429]
Staff needs ability to upgrade client account to "commercial" account or to downgrade a "commercial" account to "residential" account.

**Comment by rodolfomartinez** [comment]
We should have the ability to do this, but should be manual (ie let's not try to fix legacy data via ETL).  If this requires UI dev, please clarify and re-assign

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, implemented - please confirm and close ticket.
