### ISSUE TITLE
(23) Comments Listing page

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#430]
(a) In dashboard list, show latest 25 comments and have a "see more" button at bottom

(b) Have a separate dedicated list page of all comments sorted by creation date

(c) colums: user, timestamp, comment, job ID

**Comment by rodolfomartinez** [comment]
I like this idea, but I would propose some changes:

1. What does the see more button do or where does it go?
2. So how would I find this new page? What do we call it? Prehaps "Activity"?
3. I think we can get away with just the comment and a link to the job ID - the other columns will only clutter UI

**Comment by bartmika** [comment]
@rodolfomartinez 
1. See more button will take you from the dashboard to the listing page

2. Currently the dashboard with the "see more" text can be the only way? I don't think it needs a menu item.

3. Sure thing!

**Comment by rodolfomartinez** [comment]
@bartmika 
So really it should just consist of a table labelled "Activity" with two columns:
1. Comment
2. Link to Job

Is that what you had in mind?
