### ISSUE TITLE
Clarification with the "Street Address (Extra)" Field

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#435]
**Summary**

Currently the "Address (Extra)" field under client creation is unused. 
It is far more common practice to add Apartment or Unit numbers at the front of the address in the standard address field. Example: "407-880 Kipps Ln." to represent "880 Kipps Lane, Apartment 407". 

I think removal of this field is appropriate, so we do not add more clutter and unused fields; however I would clarification on how we should proceed with this. 

Example URL from arbitrary client detail form. Examine the "Street Address (Extra)" Field
https://london.workery.ca/en/clients/summary/residential-detail/23478/edit/

**Comment by rodolfomartinez** [comment]
@bartmika - please hide "street address (extra)" for residential and commercial clients
and for commercial clients, please hide
"Neighbourhood (extra)" field [it is immediately after street saddress extra]
