### ISSUE TITLE
Jobs List - Dates?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#438]
**Summary:**
What dates do we need here?
https://london.workery.ca/en/jobs/list/

**Comment by bartmika** [comment]
@rodolfomartinez @RaymondO55 What is the status of this issue?

**Comment by RaymondO55** [comment]
Currently the "Start Date" does not represent anything meaningful. I believe it is the same as the "Creation Date". This can likely become hidden from the GUI to prevent confusion on job detail pages. Image provided for example.
![start date](https://user-images.githubusercontent.com/41381131/43280560-330753fe-90df-11e8-8eac-7e2f2227a568.png)

**Comment by rodolfomartinez** [comment]
@RaymondO55 let's discuss this today
