### ISSUE TITLE
Client Searc Results Display

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#439]
**Summary:**
When displaying search results (sample URL https://london.workery.ca/en/jobs/create/step-1/search-results?given_name=&last_name=fairley&telephone=&email_id= )
the grid elements appear in columns, so if there are two, one appears below the other. Can we change this so that results appear in rows before columns?
For example, search results currently display as:
1
2

I would like it to display as:
1 2

Please ensure that this does not break responsive display, especially iPad

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its fixed sir
