### ISSUE TITLE
New Report - Associate List

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#446]
**Summary:**
This report will simply generate a list of all Associates, their DOB, and their skill sets separated by pipes. The page where the report is run should give the option to choose
1. Only Active Associates
2. All Associates

**Comment by bartmika** [comment]
@RaymondO55 The report has been created, please verify and close issue once approved. https://london.workery.ca/en/report/9/

@rodolfomartinez FYI

**Comment by RaymondO55** [comment]
![birthday report](https://user-images.githubusercontent.com/41381131/43154824-a910e7d8-8f43-11e8-9a6d-ec86b2c44271.png)

Seems to have an issue. Image provided.
