### ISSUE TITLE
Add Commercial Associate

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#447]
**Summary:**
I would like to establish a process to add commercial associates, the same way we have commercial clients

**Comment by bartmika** [comment]
Hi @RaymondO55, I plan on making time in the near future to implement this. May your team come up with a solution so I may begin implementing this enhancement? Thank you and looking forward!

**Comment by bartmika** [comment]
@rodolfomartinez Could your team come up w/ a process and write the details in this ticket?
