### ISSUE TITLE
Cannot Add Announcements

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#455]
We cannot create announcements because the associates do not appear in the drop down menu. Image provided for clarification.
![announcements page](https://user-images.githubusercontent.com/41381131/43162759-0fc90530-8f5a-11e8-883e-9126f3606537.png)

**Comment by bartmika** [comment]
@RaymondO55 Sorry this was a bug on our end. Issue is fixed, please verify.

**Comment by rodolfomartinez** [comment]
Fixed.
