### ISSUE TITLE
Insurance Expired

### ISSUE THREAD

**Issue by SusanFaiarley** [over55/workery-django#459]
If an Associates insurance has expired, they should NOT be allowed any new jobs

A valid insurance date should be a required field

**Comment by bartmika** [comment]
Hi @rodolfomartinez, what is the status of this issue?

**Comment by rodolfomartinez** [comment]
@bartmika - we need to update our member data first, then we can come up with the correct process

**Comment by rodolfomartinez** [comment]
@susanfaiarley - agreed this is important but I think we need a better process. I am closing this so we can look at creating an “alerts” function
