### ISSUE TITLE
Reports Page

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#46]
Hey Rodolfo, 

May I please get the design of the page, the html code and the content so I can implement the reports pages? Also feel free to right your vision and details here about this.

**Comment by rodolfomartinez** [comment]
@bartmika the first step is to replicate this page exactly as the index
http://inthought.pw/reports/

After that, each sub page would look almost identical - for example sales eports would have 1 or 2 tiles/icons for the reports of type "Sales". We can review this in person if need be

**Comment by rodolfomartinez** [comment]
@bartmika - I will review with Susan and get you exactly the data we desire in each

**Comment by bartmika** [comment]
Here is an example of the report page.

![screen shot 2018-05-20 at 9 26 03 pm](https://user-images.githubusercontent.com/5767602/40286392-8546e214-5c74-11e8-9ca6-fd94c7f2a1c6.png)

May you please provide me the following items for each report. 

Report Title: The title which will display in the GUI.
Report Desc: The short description of the GUI.
Report Icon: The icon to use for that GUI

**Comment by bartmika** [comment]
Majority of reports finished, will close ticket and create separate tickets.
