### ISSUE TITLE
Workery Reports - analysis

### ISSUE THREAD

**Issue by SusanFaiarley** [over55/workery-django#462]
Each report in Workery should have consistent names
EG   -  Service Fees Due (on the main page)
  Within the report…. “Due Service Fees Report”

 
  Report #1  Service Fees Due
1)  Add Assignment date to report -  report based on assignment date, however the report states completion date.     Would be nice to have BOTH within the report, however the specifics of the report are based on the Assignment Date 
2)  NAME of REPORT within the report
3)  Add the date range that was selected within the report
4)  Add the date that the report was created (date stamp)
 
Note that there is a spelling error……Completed and paid
 
Headings -  JOB DUE FEE     (should be Service Fee Due)
                     Job Labour      (should be Labour Charged)
                     Skill Sets are blank

 
REPORT #2   Associate Jobs
1)	 Based on assignment date, however only completion date is within the report
it would be advantageous to have BOTH assignment date AND completion date within the report
2)	2)  NAME of REPORT within the report
3)	3)  Add the date range that was selected within the report
4)	4)  Add the date that the report was created (date stamp)
5)	Headings -  JOB DUE FEE     (should be Service Fee Due)
6)	                     Job Labour      (should be Labour Charged)
7)	                     Skill Sets are blank

  
Report #3    Service Fees paid by Skill Sets Report
1)	Date should be based on Assignment Date 
2)	Yet BOTH Dates on the report would be awesome
2)  NAME of REPORT within the report
3)  Add the date range that was selected within the report
4)  Add the date that the report was created (date stamp)

Report #4    Job Cancellations Reasons Report
1)	SAME AS ABOVE

Report #5   Associate Insurance
Report Names do not match
Associate Commercial Insurance Report        SHOULD BE ASSOCIATE INSURANCE
NAME of REPORT within the report
Add the date range that was selected within the report
Add the date that the report was created (date stamp)
Only 6 Associates listed ???
We have 47 Active Associates as per the DASHBOARD 
Add the type of insurance the Associate has
*O55 CGL
*CGL
*OPCF 6A
*SNOW REMOVAL
*WSIB
*Tree Removal

 

Report #6   Associate Police Check
Name of report “Associate Policy Check Due Date Report”  
Names do not match

NAME of REPORT within the report
Add the date range that was selected within the report
Add the date that the report was created (date stamp)
25 Associates only were printed on the report ?
Yet Dashboard reflects 47 Associates

Report #7    Associate Birthdates
NAME of REPORT within the report
Add the ACTIVE ASSOCIATE,  the parameters of the report
Add the date that the report was created (date stamp)

Report #8  Associate Skill Sets Report
NAME of REPORT within the report
Add  the parameters of the report as selected
Add the date that the report was created (date stamp)

Report #9  Client Addresses
NAME of REPORT within the report
Add  the parameters of the report as selected    ACTIVE or INACTIVE
Add the date that the report was created (date stamp)

Report #10    Jobs Report
From Date  (should say    From Assignment Date)
To Date  (should say      To Assignment Date)
NAME of REPORT within the report
Add the date range that was selected within the report
Add the date that the report was created (date stamp)
Associate is actually the client and visa-versa  (Titles within the report are backwards)
Add Job Completion Date as well as Assignment Date

Report #11  Commercial Jobs Report
From Date  (should say    From Assignment Date)
To Date  (should say      To Assignment Date)
NAME of REPORT within the report
Add the date range that was selected within the report
Add the date that the report was created (date stamp)
WSIB # that Associate has on file
Why are some skill sets missing   ?

**Comment by SusanFaiarley** [comment]
Bart - I have a PDF with print screens if that would assist you
I just cannot drop and drag it onto GitHub
let me know if you want me to email it to you
Thx Susan

**Comment by rodolfomartinez** [comment]
Replacing with updated tickets. Will close this one.
