### ISSUE TITLE
New Pagination UI

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#463]
**Summary:**

Please replace current pagination for all pages with something like this, styled to fit the workery:
![5f9e31fc-9f70-4d77-9a41-68962ead0d50](https://user-images.githubusercontent.com/7537946/43405615-3ce6757e-93e8-11e8-9b3b-3b41af670337.jpeg)

**Comment by bartmika** [comment]
That looks like great GUI! Excited to see this.

**Comment by rodolfomartinez** [comment]
@KPSbuttar - status?

**Comment by rodolfomartinez** [comment]
Looks hood! Please implement on all pages

**Comment by bartmika** [comment]
@KPSbuttar What is the status of this issue?

**Comment by KPSbuttar** [comment]
https://london.workery.ca/en/closed-tasks/?page=12

Its done

**Comment by rodolfomartinez** [comment]
@KPSbuttar this works at the link cited, but does not appear to be implemented on all other pages. For example: 
https://london.workery.ca/en/clients/summary/

is missing the pagination UI at the bottom

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika I have implemented this pagination UI on all pending pages, please review all sir and if i missed any page please message me. Thanks
