### ISSUE TITLE
Job details being cached?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#464]
**Summary:**
When adding a job, and then adding another, sometimes the browser caches the details, so it looks like the job is being created with the same details as the previous job.  Once a user hits "Save" to add the job, the cache should be cleared, as this is confusing to the user

@KPSbuttar - please verify if this is a UI or backend issue.

To test: create a job, on the last step cancel, then add a job again.  If you want to test on prod, search for client "Rodolfo Martinez" and add a job for them.

**Comment by bartmika** [comment]
@rodolfomartinez I'll take a look at this first, it may have something to do with issue #428.
