### ISSUE TITLE
What does the job number represent?

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#465]
What does this number represent? If it represents active jobs which are assigned and are in progress with a 48 hour followup task OR Completion Survey task, shouldn't the number be equal to or be relatively close to the number of tasks that exist? What does this number actually represent and what does it not account for? Image provided for clarification.
![jobs number representation](https://user-images.githubusercontent.com/41381131/43406593-9802c01e-93ea-11e8-9667-852c199d1914.png)

**Comment by rodolfomartinez** [comment]
@bartmika Bump

**Comment by bartmika** [comment]
@rodolfomartinez @RaymondO55 Currently it only returns how many jobs have the `state` value as `in-progress`. See via https://github.com/over55/workery-django/blob/master/workery/tenant_dashboard/views/web_views.py#L57

Please let me know how you'd the numbers counted for if this does not work.

**Comment by rodolfomartinez** [comment]
@bartmika - it should be any job that is active - could be pending, assingned or in progress

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, may you please verify this issue and close it? Also note the criteria items are:

* Job is new
* Job is pending
* Job is ongoing
* Job is in progress

**Comment by bartmika** [comment]
@RaymondO55 Not necessarily. The jobs count does not contain "completed but unpaid" entries and the task item have some jobs which are "completed but unpaid" - as a result this explains the vast difference in numbers. May you please investigate and provide direction? Thanks!

**Comment by RaymondO55** [comment]
@bartmika As far as I am aware, the task should not include "Completed and unpaid jobs" because those are handled in the Financial section. Can the parameters of what both these values are tracking are?

**Comment by bartmika** [comment]
@RaymondO55 Confirmed, may you please confirm now? Thank you.
