### ISSUE TITLE
Pending Orders, Update Summary Information

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#466]
The summary table for pending job orders need the client information to easily relay the information if the pending associate calls back and accepts the job. Images provided for clarification.
![pending summary page](https://user-images.githubusercontent.com/41381131/43413152-3f493c88-93fd-11e8-8c0e-ef145e3df867.png)
This page needs the same fields the assignment summary table has
![assignment summary table](https://user-images.githubusercontent.com/41381131/43413170-4cd9ffb8-93fd-11e8-8722-d565edf75187.png)

**Comment by bartmika** [comment]
@RaymondO55 Fixed, please close if it meets your requirements.
