### ISSUE TITLE
Report #1

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#470]
**Summary:**
Report #1 needs to have its template updated, and there appear to be errors with some report data. I have emailed the updated template (.csv), and also we need to adjust the following:

- In the template I have renamed "Job Due Fee" column to "Service Fee" 
- Skillsets appears to only work with jobs that only have one skill set attached. Can we verify that multiple skillsets are being separated by pipes?

**Comment by bartmika** [comment]
![screen shot 2018-08-01 at 8 47 59 pm](https://user-images.githubusercontent.com/5767602/43556148-37971f20-95cc-11e8-9e31-64c7b87f92af.png)

I confirm multi-skillsets are rendered with pipes.

**Comment by bartmika** [comment]
> Skillsets appears to only work with jobs that only have one skill set attached. Can we verify that multiple skillsets are being separated by pipes?

The reason for this is because we are listing the job-skills from the job and not the associate. You will need to update the jobs to fix the data.

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, may you please verify this issue?
