### ISSUE TITLE
Report #2 - Associate Jobs

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#471]
**Summary:**
Report #2 needs to have its template updated, and there appear to be errors with some report data. I have emailed the updated template (.csv), and also we need to adjust the following:

-I have added header data
- Deleted first two columns and added others
- In the template I have renamed "Job Due Fee" column to "Service Fee" 
- Skillsets appears to only work with jobs that only have one skill set attached. Can we verify that multiple skillsets are being separated by pipes?

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, please verify this ticket is acceptable.
