### ISSUE TITLE
Report #4

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#473]
**Summary:**
I have emailed new template with sample data.  For some jobs, cancellations reason is not being displayed (perhaps it was somehow not entered?)
Also, multiple skillsets are not displaying correctly.

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, may you kindly QA this ticket?

**Comment by bartmika** [comment]
@RaymondO55 What is the status of this issue?
