### ISSUE TITLE
Report #5 - Associate Insurance

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#474]
**Summary:**
I have emailed a new report template with updated header info header info

**Comment by bartmika** [comment]
Hi @RaymondO55 , may you please take a look and QA? Thank you!

**Comment by RaymondO55** [comment]
Hey @bartmika wed like to change some parameters for this report to pull all the useful information we need. Can we get the report to pull up all active members that exists on Workery regardless of the other fields? This way if we see that some information is blank, we can check if we have the info on file or need to contact the associate. Here is the template we would like this report to follow:

[associate_commercial_insurance_due_dates-template-SF.xlsx](https://github.com/over55/workery-django/files/2254699/associate_commercial_insurance_due_dates-template-SF.xlsx)

**Comment by bartmika** [comment]
Hi @RaymondO55, your recent comment was implemented. May you please confirm this report is acceptable?

**Comment by RaymondO55** [comment]
@bartmika The report itself seems acceptable but I found an issue with the Auto Insurance field. See #486

**Comment by bartmika** [comment]
@RaymondO55 You are correct, the missing auto insurance field issue (via #486) is causing this report to not generate the fields. I've patched up #486 so you should confirm this report now working. FYI, you will need to update all the associate records with the auto insurance expiry data before testing this issue out again.

Please review and close this issue when verified. Thanks!
