### ISSUE TITLE
Report #6 - Associate Police Check 

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#475]
**Summary:**
I have emailed a new report template with updated header info header info

Also, the column titled Associate Commercial Insurance should be "Police Check Due Date" and pull in the correct data

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, may you please check this ticket and confirm it? Thank you.

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, what is the status of this ticket?

**Comment by RaymondO55** [comment]
@bartmika Can we have this report pull ALL active associates and sort by expiry date?

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, this reports to be already returning all active associates and sorted by the newest to oldest expiry date. May you please let me know which records in this report are either not in order or not active associates. Thanks!

**Comment by bartmika** [comment]
@RaymondO55 Ah I understand! Thank you for the clarification - so I added filtering to remove any blank dates and all dates are older then todays date. I removed this and it should work now. Please verify and close issue if the fix was acceptable.
