### ISSUE TITLE
Report #10 - Jobs

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#480]
**Summary:**
I have emailed a new template with added header info and new columns. Also, I have switched the labels for Associate and Customer as the report was putting the Associate Name where the Client Name goes and vice versa.

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, may you please verify this issue can be closed and proceed to closing it? Thank you.

**Comment by bartmika** [comment]
> Also, I have switched the labels for Associate and Customer as the report was putting the Associate Name where the Client Name goes and vice versa.

This was a typo on my end. My apologies! I've switched the two so now associate and then client get listed - I did this to be more consistent with the other reports.
