### ISSUE TITLE
Report #11 - Commercial Jobs

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#481]
**Summary:**
I have emailed a new template for this report - it adds header data and 1 column (assignment date).

Also, it appears to be pulling in ALL clients. ONLY commercial clients and their corresponding jobs should be here.

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, may you please QA this? Thank you!

Please note, if there are any problems, may you please provide example of commercial jobs/clients for me to do research on for fixing any bugs you may find.

**Comment by rodolfomartinez** [comment]
@SusanFaiarley - please review report for accuracy

**Comment by rodolfomartinez** [comment]
@RaymondO55 - please review for accuracy
