### ISSUE TITLE
Vehicle Type 

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#485]
**Summary:**
Missing Car as a type - was it somehow deleted? Also, can we add a vehicle setting - it also appears that everyone has truck and van, and when I deleted car from one associate did it delete it from everyone?

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, I've created the GUI for adding/deleting `vehicle types`, see: https://london.workery.ca/en/settings/vehicle_types/

**Comment by bartmika** [comment]
@KPSbuttar Please implement this API endpoint to load up the vehicle types. https://github.com/over55/workery-django/blob/9b1f45a15dac6e32e26d10b089932d5f5c62cd21/workery/templates/tenant_api/vehicle_type_api_js.html#L84

If you look [here](https://london.workery.ca/en/members/summary/detail/6142/edit/) you'll notice the vehicle types does not work. Please implement that code I provided so there will work exactly like skill sets (except we will only be pulling vehicle types).

@rodolfomartinez FYI

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, what is the status of the issue?

**Comment by bartmika** [comment]
@KPSbuttar @rodolfo-over55 Status of this?

**Comment by rodolfomartinez** [comment]
@KPSbuttar bump?

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its done i tried a lot and UI implementation is complete. ONLY issue is sir django {{ vehicle_types }} not fetching values. Can you please check ASAP!! then this ticket will be complete.

Regards

**Comment by rodolfomartinez** [comment]
@KPSbuttar Please implement this API endpoint to load up the vehicle types.

workery-django/workery/templates/tenant_api/vehicle_type_api_js.html
Line 84 in 9b1f45a
     function get_vehicle_types(criteria, func_callback, func_error_callback)

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, I just checked the GUI and it looks to be working. Did you end up figuring out and fixing this?

If not can you let me know where to find the ``{{ vehicle_types }}`` code?

Also, if this issue is fixed, can you assign it back to @rodolfomartinez ? Thank you!

**Comment by bartmika** [comment]
Never mind, closing now.
