### ISSUE TITLE
Auto-Insurance Field is Missing

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#486]
The Auto-Insurance Field for Associate Members are not being saved. It does not appear in the associate summary, and when the field is filled out via edit member it does not save the information when you go back to edit the associate. Images provided for clarification. 
![autoinsurance](https://user-images.githubusercontent.com/41381131/43651523-ac496b58-9710-11e8-94fa-c039ed5511a4.png)
![auto insurance on summary](https://user-images.githubusercontent.com/41381131/43651536-afaf3796-9710-11e8-9da2-c01f078975b1.png)

**Comment by bartmika** [comment]
@RaymondO55 Confirmed bug! Issue fixed, please confirm this issue is acceptable now. Thanks!
