### ISSUE TITLE
Payment Date should be a Financial only field 

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#487]
We have an issue with editing jobs because the page has a mandatory "Payment Date" field. This prevents us from being able to proceed with any edits to a job while the job needs assignment or is in progress. This field should only appear in the financial section for Completed jobs. Image provided for clarification.
![payment date in job editiing](https://user-images.githubusercontent.com/41381131/43656882-0b4c8638-9722-11e8-8620-941fefdb66b7.png)

**Comment by rodolfomartinez** [comment]
@KPSbuttar - is this a GUI issue which you can solve, or is this for @bartmika ?

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, confirmed - may you please check and close issue if this acceptable? Thanks!
