### ISSUE TITLE
Report run dates incorrectly populated

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#488]
**Summary:**
When running a report, the run date is incorrectly displayed.  If I run a report and open in Excel on my iPad, year shows as 2008

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, I changed the CSV date/datetime outputting format to be dd/mm/yyyy. May you please verify MS Excel loads up without issue on your end? Please close this issue if you consider it closed.
