### ISSUE TITLE
Ongoing comments redirects to incorrect pathway

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#491]
Clicking to view the comments from the ongoing job task summary screen redirects the page to the unassign page. Image provided for clarification.
![ongoing summary](https://user-images.githubusercontent.com/41381131/44042225-bb0d139e-9eed-11e8-8426-dcd4019424a9.png)
![ongoing unassign](https://user-images.githubusercontent.com/41381131/44042235-c064e736-9eed-11e8-9e16-2d74e48530ae.png)

**Comment by bartmika** [comment]
Hi @RaymondO55, bug has been fixed, please verify and close issue when ready.
