### ISSUE TITLE
Can we manual access to the Ongoing Job monthly task?

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#492]
Currently, we cannot access the monthly task that is created for all ongoing jobs for management staff. They can only be accessed on the 1st of each month when the task is created. Can we get manual access to this task so we can create completed job orders to process invoices at any given time? Image provided for clarification.
![create visits button](https://user-images.githubusercontent.com/41381131/44042908-8685c894-9eef-11e8-8183-b679f699d291.png)

**Comment by bartmika** [comment]
@RaymondO55 Implemented as per request, please try and confirm it is working as required. Thanks!
