### ISSUE TITLE
Volunteer Request - Skill set sorting

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#495]
We have a request from a volunteer to make the skill sets appear in alphabetical order for convenience. They are aware of the ability to type as a search function but it still makes sense to also make it alphabetical. Image provided for clarification. 
![skill set sorting](https://user-images.githubusercontent.com/41381131/44167531-684cb500-a09c-11e8-9a36-bfdddfddc85d.png)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, I've updated the job creation , skill set listing page (in settings) and a few other places. Please verify if this ticket is acceptable or if you find other areas of this site that requires this ordering.
