### ISSUE TITLE
Ongoing Jobs - Pending

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#496]
I found the origin of this bug, it appears like this when an ongoing job is set to pending with an associate
![ongoing bugs1](https://user-images.githubusercontent.com/41381131/44167824-38ea7800-a09d-11e8-860d-b8409cd20005.png)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, I tried https://london.workery.ca/en/tasks/pending/search/results/?keyword=pending (as in the picture) and I am unable to replicate. May you please provide a full set of instructions to replicate this issue? I will work on this once I am able to replicate it. Thanks!

**Comment by RaymondO55** [comment]
@bartmika  It occurs when an ongoing master form is marked as pending while trying to assign an associate. This is more of a visual bug, as the task, job and other features of the job can be accessed and processed. I will leave the test order Master Ongoing Order 65 as pending for you to see.
