### ISSUE TITLE
Ongoing Jobs - Unassignment and Tasks

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#497]
I found in my testing when unassigning an ongoing master form it breaks the workflow and creates a 48 follow up task instead of a re-assignment task. Image displays end result
![reassignment breaks tasks](https://user-images.githubusercontent.com/41381131/44167901-6fc08e00-a09d-11e8-9108-70267460b536.png)

**Comment by bartmika** [comment]
@RaymondO55 Bug was fixed, now and moving forward, when you unassign an ongoing job, a pending task gets created for assigning associate. Please test out and confirm.
