### ISSUE TITLE
Activity sheet being overwritten

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#499]
When jobs are being reassigned, all of the information in the activity sheet is being marked with the newly assigned associate instead of retaining the information of the original associate who accepted/declined the job. Image provided for clarification

![activity sheet overwritten](https://user-images.githubusercontent.com/41381131/44212789-4dc91900-a13a-11e8-9638-acb26e6af855.png)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, I confirm this bug. Thankfully this bug does not affect the data integrity of the records, it was simply a GUI bug. You should see everything working now. Please assign close when verified.
