### ISSUE TITLE
Report #2 - Associate Jobs

### ISSUE THREAD

**Issue by SusanFaiarley** [over55/workery-django#500]
Date Columns - can they be re-formatted to reflect MM - DD - YY
so that we can sort them within Excel

Service Fee & Job Labour -  currently C$0.00
can we remove the C
and format these two columns to currency

Thank you

**Comment by bartmika** [comment]
Hi @RaymondO55, task has been completed for both the specified (1) formatting and (2) removing the "C" from currency.

**Comment by SusanFaiarley** [comment]
AWESOME Bart - looks great
Glad to see that all date formating and currency is re-set !!!!
Thank you !!!
