### ISSUE TITLE
Ongoing Jobs not spawned with Skill Sets

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#502]
The job orders created from master ongoing job orders are not spawned with the skill sets or descriptions recorded. For example Job Order 24650 does not have a description or skill set because it was spawned from Master Order Form 67. Can the job orders created in this manner retain the information from the master order form? Also, can we have a track the master order form in the job details? Thanks. Images included for clarification.

![ongoing job spawn details](https://user-images.githubusercontent.com/41381131/44347775-baa82000-a466-11e8-9225-4e0e4c503213.png)

![master order form skills](https://user-images.githubusercontent.com/41381131/44347793-c693e200-a466-11e8-8545-13dd59f97cfe.png)

**Comment by bartmika** [comment]
Hi @RaymondO55, bug found and fixed. New jobs will get created with `description` and `skill_sets` now; however, previously created jobs did not you will need to manually update those records. Please verify and close ticket when ready. Thanks.
