### ISSUE TITLE
Ongoing Jobs are not creating tasks properly

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#505]
Ongoing jobs are not creating proper 48 hour follow up tasks. The task exists but is unable to proceed to the next steps. Image provided for clarification.

![ongoing tasks bug](https://user-images.githubusercontent.com/41381131/44360817-05875f00-a48a-11e8-97fa-81346c31aee3.png)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, may you please let me know the steps to take to replicate this problem? I do not know how to replicate it. More details would be appreciated. Thank you!

**Comment by RaymondO55** [comment]
@bartmika I am completely unsure of how this task was created. I can't seem to reproduce it either, I was just reporting the bug associated with the task. We do want Ongoing jobs to create 48 hour follow ups as mentioned in #506 however, this seems to be an outlier.

**Comment by bartmika** [comment]
Hi @RaymondO55, I've update the code to generate 48h tasks when a single work order gets created from the master form. Please verify it works for your team. Also to move forward with this outlier task, I can delete it but require your permission - please advise. Thank you!

**Comment by RaymondO55** [comment]
@bartmika 

> I've update the code to generate 48h tasks when a single work order gets created from the master form.
Please revert this change. A detailed procedure of changes will be provided in #506 

> I've update the code to generate 48h tasks when a single work order gets created from the master form.
Please proceed with this

**Comment by bartmika** [comment]
@RaymondO55 Confirmed! Please verify my latest change.
