### ISSUE TITLE
Ongoing follows incorrect process

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#506]
Currently, ongoing master orders are not following the standard process. When assigning an ongoing job, it does not create a 48 hour follow up task as it should. Instead, it is creating an Ongoing Update task dated at the end of the month. Ongoing jobs should follow the same procedure as standard jobs after assignment; creating a 48 follow up task, and a Completion Survey task. Images provided for clarification.

![ongoing wrong task](https://user-images.githubusercontent.com/41381131/44404765-995a3900-a525-11e8-9ec8-e3ee564af8ef.png)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, may you please provide me more details on how you expect the tasks process to work so I may review the code and make fixes when necessary. Thanks and my apologies for any inconveniences this ticket is causing.

**Comment by RaymondO55** [comment]
@bartmika The process is very close to where we want it to be. Here are of the list of changes that need to be implemented.

- Revert the changes made in #505 

- After assigning an associate to a Master Ongoing Form, a 48 hour task should be created using the Master Ongoing Form. The process should function identically like a normal job order process, however; a child job order will not exist at this stage.

- When the 48 hour task is processed, a Completion Survey task should be created using the Master Ongoing Form. Again, a child job order will not exist at this stage, so the Master Ongoing Form must be used.

These two tasks should only be processed ONCE per Master Ongoing Form; as if it were a standard job order.

For clarification, the ongoing job processes should be treated the same way as standard jobs so that we follow proper procedure to see if our associates are contacting their clients and so we can collect feedback accordingly. The master forms exists so that we can create multiple job orders for the purpose of processing multiple, and more accurate numbers in the financial department. This is also why the spawned child jobs are immediately marked as "Completed and Unpaid." The initial procedure for the front line should not change except for the clicking on the radio button to mark the job as ongoing.

- During the creation of an ongoing job, I would like the following field altered as shown in the image below. I would like the information from this field retained and displayed on the Ongoing Summary and Details pages.

![ongoing frequency](https://user-images.githubusercontent.com/41381131/44472888-1e645180-a5fd-11e8-8584-ad869af3be2c.png)

![ongoing summary page](https://user-images.githubusercontent.com/41381131/44473044-80bd5200-a5fd-11e8-8c88-74a0f405954e.png)

![ongoing details page](https://user-images.githubusercontent.com/41381131/44473076-8b77e700-a5fd-11e8-985b-a18b8e8ceeaf.png)

**Comment by bartmika** [comment]
@RaymondO55 I am still working on this issue, please do **not** QA. Here is my progress so far:

> Revert the changes made in #505
Done


> After assigning an associate to a Master Ongoing Form, a 48 hour task should be created using the Master Ongoing Form. The process should function identically like a normal job order process, however; a child job order will not exist at this stage.

Done


> When the 48 hour task is processed, a Completion Survey task should be created using the Master Ongoing Form. Again, a child job order will not exist at this stage, so the Master Ongoing Form must be used.

Done


> These two tasks should only be processed ONCE per Master Ongoing Form; as if it were a standard job order.

Done


> For clarification, the ongoing job processes should be treated the same way as standard jobs so that we follow proper procedure to see if our associates are contacting their clients and so we can collect feedback accordingly. The master forms exists so that we can create multiple job orders for the purpose of processing multiple, and more accurate numbers in the financial department. This is also why the spawned child jobs are immediately marked as "Completed and Unpaid." The initial procedure for the front line should not change except for the clicking on the radio button to mark the job as ongoing.

**TODO**


> During the creation of an ongoing job, I would like the following field altered as shown in the image below. I would like the information from this field retained and displayed on the Ongoing Summary and Details pages.

**TODO**

**Comment by RaymondO55** [comment]
@bartmika 

> For clarification, the ongoing job processes should be treated the same way as standard jobs so that we follow proper procedure to see if our associates are contacting their clients and so we can collect feedback accordingly. The master forms exists so that we can create multiple job orders for the purpose of processing multiple, and more accurate numbers in the financial department. This is also why the spawned child jobs are immediately marked as "Completed and Unpaid." The initial procedure for the front line should not change except for the clicking on the radio button to mark the job as ongoing.

These are not really instructions, just an explanation of why I have designed the system in this fashion. With the previous changes implemented and tested, consider this part done as well

**Comment by bartmika** [comment]
@RaymondO55 @rodolfomartinez Hi guys, so I've implemented this ticket except this paragraph.

> During the creation of an ongoing job, I would like the following field altered as shown in the image below. I would like the information from this field retained and displayed on the Ongoing Summary and Details pages.

May you please review this and provide me more details. The reason being that if I change as specified the follow needs to be taken into account:

1. This field is used as the date the associate+client meet, what do we do if we replace it?

2. If we save the frequency ... what does it do? Currently the update master form tasks get created at the first of the month, how would the frequency affect it? If this field is strictly for record keeping purposes then that's no problem.

Please advise! Thank you.

**Comment by RaymondO55** [comment]
@bartmika 

> This field is used as the date the associate+client meet, what do we do if we replace it?

The "When should the job start?" field should mark the meeting date. 

> If we save the frequency ... what does it do? Currently the update master form tasks get created at the first of the month, how would the frequency affect it? If this field is strictly for record keeping purposes then that's no problem.

The field is to simply provide useful information that is exclusive to ongoing jobs, no special functions required.

**Comment by bartmika** [comment]
Hi @RaymondO55, task has been completed, please verify and close ticket when ready.

**Comment by RaymondO55** [comment]
@bartmika The final items you implemented are working as intended.

After speaking with Rodolfo, we need the following changes to be implemented to finally get Ongoing where we want it to be. All images will be using the test Ongoing Master Form 80.

**Ongoing Job Details - Edit Page**

We need something clarified
- What is the "Idle" state, and how does it differ from "Running" and "Terminated"

We need a fully fleshed out edit page for Ongoing Master Forms.  The editable fields should include everything circled in the image below, as well as the field mentioned under Ongoing Follow Up Process

![ongoing edit sheet](https://user-images.githubusercontent.com/41381131/44873004-06c44300-ac65-11e8-8a7f-a1494b47a3ac.png)


**Ongoing Follow Up Process**

The current function is an old process that we need to be re-purposed. Here are the following changes with an image for clarification. We also suspect this may be the cause of issue #520 

- This Dropdown currently has options for 1/2/3 weeks. The options need to be changed to "Never", "Monthly", "Quarterly" and "Annually"
- This field should default to "Quarterly"
- This field needs to be hidden from the GUI during the job creation phase. It should appear in the Ongoing Job Details - Edit Page as mentioned above

![ongoing follow up](https://user-images.githubusercontent.com/41381131/44874923-ae903f80-ac6a-11e8-8b50-134cf716fc2c.png)

**Ongoing Frequency**

The only change here is to hide this field until "Ongoing" is selected. Exactly like how "Follow Up" works now

**Comment by bartmika** [comment]
@RaymondO55 @rodolfomartinez 

> What is the "Idle" state, and how does it differ from "Running" and "Terminated"

Idle and terminated are both similar since no tasks get created. The only difference is that when something is ‘terminated’ then the task is permanently closed and cannot be edited, but if set in `idle`, you are allowed to edit it.


> We need a fully fleshed out edit page for Ongoing Master Forms. The editable fields should include everything circled in the image below, as well as the field mentioned under Ongoing Follow Up Process 

Done


> The only change here is to hide this field until "Ongoing" is selected. Exactly like how "Follow Up" works now

Done

> [...Remove the follow up field...]

Done


> This field should default to "Quarterly"

Did not do, it’s best to let user select the option. I’ve added a help comment.


> This Dropdown currently has options for 1/2/3 weeks. The options need to be changed to "Never", "Monthly", "Quarterly" and "Annually"

Done
