### ISSUE TITLE
Report - Associate Job Report

### ISSUE THREAD

**Issue by SusanFaiarley** [over55/workery-django#507]
Bart I do not believe this report is pulling the proper data
I ran the report from March 1 - Aug 20 and it is reflecting
No service fees paid and no completed jobs for
driving
electrical
handyman
housekeeping
etc

**Comment by bartmika** [comment]
Hi @SusanFaiarley, thank you for letting me know - I've taken a look in report number 2 ("Associate Jobs Report") and I was not able to replicate this issue, is there any particular choices you've selected that is causing this? Please let me know the choices you selected and I'll look into this issue. Thank you and my apologies for any inconvenience.

**Comment by bartmika** [comment]
@RaymondO55 @rodolfomartinez Hi, what is the status of this issue? Thanks!

**Comment by RaymondO55** [comment]
@bartmika Implementing the changes in #510 and #511 should solve the problems we have been having with reports.

**Comment by bartmika** [comment]
@RaymondO55 Assigned back to you, when #510 and #511 have been completed, please verify this.
