### ISSUE TITLE
Create alerts

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#509]
**Summary:**

We need to create alerts for non-job order related items, primarily expired insurance

**Comment by rodolfomartinez** [comment]
A mockup exists on inthought.pw; we should use that as a starting point. I do see this as something that should likely happen post unit testing

**Comment by bartmika** [comment]
Created ETL which will automatically add associates with expired commercial insurance into away log AND send email to management staff. This was closed in ticket #610 as a result this issue is closed too.
