### ISSUE TITLE
Surveys are not properly recorded

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#511]
The Survey Score does not accurately record the scores of the surveys conducted as shown in this report. If a Survey was not conducted, the score fields should be blank, instead of automatically marking them with a score of 5. 

![survey report](https://user-images.githubusercontent.com/41381131/44534105-022be780-a6c5-11e8-9ec2-4668251e170c.png)

**Comment by bartmika** [comment]
Hi @RaymondO55, I've made some fixes, may you please confirm now?

**Comment by RaymondO55** [comment]
@bartmika I actually wanted the opposite changes to be made. Where if "Survey Conducted" field = 0, then survey score information should be deleted, else make no changes. Image provided for instructions

![survery changes](https://user-images.githubusercontent.com/41381131/44587231-534ce180-a780-11e8-94ac-10ae6574cb5e.png)
.

**Comment by bartmika** [comment]
Hi @RaymondO55, I added back `was_survey_conducted`, may you please run and confirm?

(Also if not, may you please provide more details on how to replicate your issues?)

Thanks,

**Comment by RaymondO55** [comment]
@bartmika Thank you for retrieving the "Survey Conducted" data, but the following changes still need to be made. Image provided with instructions.

![score report changes](https://user-images.githubusercontent.com/41381131/44856416-53932400-ac3b-11e8-9df0-943fa6d9c8f6.png)

**Comment by bartmika** [comment]
@RaymondO55 

> Score data refers to all of the fields that add up to, including, the total score. If a survey was not conducted the data should not exist or effect an associates total score.

Confirmed, thank you for the clarification and image. Task completed, please verify.
