### ISSUE TITLE
Issue with the GUI?

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#513]
Suddenly around 3pm Friday Workery has taken this appearance and is giving a security warning

![gui](https://user-images.githubusercontent.com/41381131/44604219-2c5bd300-a7b3-11e8-937e-9137300db95e.png)

![security](https://user-images.githubusercontent.com/41381131/44604232-367dd180-a7b3-11e8-9f7f-a49472bc30ea.png)

**Comment by bartmika** [comment]
@RaymondO55 @rodolfomartinez This issue was caused by the `lets-encrypt` linux app now properly renewing the ``ssl certificate``. I wrote code the [following tutorial](https://github.com/over55/workery-django/wiki/CentOS-7-additional-improvements) on setting up the auto-renew app but it looks like we are getting this error:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/workery.ca.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert is due for renewal, auto-renewing...
Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',)
Attempting to renew cert (workery.ca) from /etc/letsencrypt/renewal/workery.ca.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',). Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/workery.ca/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/workery.ca/fullchain.pem (failure)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)
```

I will investigate and fix this issue.

**Comment by bartmika** [comment]
@RaymondO55 @rodolfomartinez  Fixed! I created an API key in DigitalOcean and integrated the `letsencrypt` app to automatically renew while speaking with `DigitalOcean` via this article https://certbot-dns-digitalocean.readthedocs.io/en/latest/
