### ISSUE TITLE
[QA Server] Cannot create tenant

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#516]
**Summary:**
On workery.ca, after filling in tenant info and submitting, I get a blank screen.
If I try to view franchises after, it was NOT created
![d7aefcf0-5ee6-431a-a4c1-c95fbdf90753](https://user-images.githubusercontent.com/7537946/44725984-b0100b00-aaa4-11e8-8295-973a7e4e1bd6.png)
![0e0498d3-5ef9-419d-8e4e-e84bd6ff5e99](https://user-images.githubusercontent.com/7537946/44726054-d8980500-aaa4-11e8-8a21-0c9da937a471.png)

**Comment by bartmika** [comment]
@rodolfomartinez  Odd, I managed to get it loaded on my dev machine. I'll see what happened in QA.

**Comment by bartmika** [comment]
@rodolfomartinez  I was able to successfully create a tenant.

![screen shot 2018-08-28 at 7 10 25 pm](https://user-images.githubusercontent.com/5767602/44755904-183b0d00-aaf6-11e8-974d-65d9eb860b39.png)

May you please let me know what steps you've taken to replicate this issue?

**Comment by bartmika** [comment]
@rodolfomartinez I tried replicating your problem on ``iPad Pro`` and I was unable to get the same problem you got.

**Comment by rodolfomartinez** [comment]
@bartmika - got the samer error - not sure what is going on.  Could it be a UI issue, or could it be something related to being an @workery.ca user? Can you please send me credentials for user with a non @workery.ca email?

**Comment by bartmika** [comment]
@rodolfomartinez I believe it's fixed. May you please confirm?

**Comment by rodolfomartinez** [comment]
Fixed.
