### ISSUE TITLE
Noting News/Announcements for Associates

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#517]
**Summary:**
**To be done AFTER unit testing as this is a new feature**
Would it be possible that when someone has a new/announcement attached to them that a comment is added with the user, timestamp, and the details in a simple text format. Also, the same details when a news/announcement item is removed.

**Comment by rodolfomartinez** [comment]
yes - but as part of this, it would be good to see the timestamp and the user who created/removed the announcement

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, task completed, please verify.
