### ISSUE TITLE
Duplicate tasks are being created

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#520]
Duplicate tasks for the same job number and same task are being created. Its impossible to delete individual tasks, and if one task is processed the job order gets processed so volunteers may accidentally cancel job orders if they see both. Images provided

![duplicate tasks](https://user-images.githubusercontent.com/41381131/44790761-1745c200-ab6e-11e8-801f-6164c0d8c426.png)

![duplicate tasks2](https://user-images.githubusercontent.com/41381131/44790774-1ca30c80-ab6e-11e8-9d9b-44fb2919442a.png)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, thank you for the ticket. I am having difficulty finding replicating this issue to find a solution to fix it. Would it be possible if you let me know how you got it (detailed steps)?

What's also causing confusion here is that it appears that ticket has been closed so it's difficult to look at it.

Please advise on how to replicate.

Thanks!

**Comment by RaymondO55** [comment]
@bartmika I am also unsure about how this issue is created or steps to recreated. It is currently affecting Ongoing Master Form 76, Tasks 2015, 2132, and 2133. It appears every so often with some of the volunteers. I'm not really sure what they are doing to produce this bug

**Comment by RaymondO55** [comment]
@bartmika We suspect that the frequency field for ongoing jobs may be the cause of this issue

**Comment by bartmika** [comment]
@rodolfomartinez (1) Frequency actually does not do anything, it is just a stored variable that might aid you when you look at the details.

(2) I've added some code to attempt to fix this issue (even though I am unable to replicate it). 

May you please observe this issue and see if it happens again?
