### ISSUE TITLE
We need the ability to postpone Ongoing Tasks

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#521]
We need the ability to postpone the new Ongoing 48 hour and Ongoing Completion Survey tasks that were implemented in #506. Image provided with instructions

![pospone ongoing](https://user-images.githubusercontent.com/41381131/44795745-71985000-ab79-11e8-89f2-5f89d3300f7b.png)

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, the ability has been granted. Please test and confirm this works for your team. Thanks!

**Comment by RaymondO55** [comment]
@bartmika The function works on the 48 hour tasks, thanks Bart. However, we also need the same function for the Completion Survey task for ongoing jobs. It looks like we are also missing a cancel button for this task. image provided with instructions

![ongoing survey buttons](https://user-images.githubusercontent.com/41381131/44853199-47a36400-ac33-11e8-8546-e535930bca38.png)

**Comment by bartmika** [comment]
Hi @RaymondO55, that ability has been granted! Please confirm.
