### ISSUE TITLE
Job Report Update

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#522]
**Summary:**
For the report at this URL
https://london.workery.ca/en/report/10/

We need to add a column with the client's birthdate (Client Birthdate) immediately after the client's name.  Also, after the Skillsets column we need to add a new column titled "Job Status"

These should populate the relevant date

**Comment by bartmika** [comment]
@RaymondO55 Hi Raymond, task completed, may you please confirm?
