### ISSUE TITLE
We cannot create One Time Jobs

### ISSUE THREAD

**Issue by RaymondO55** [over55/workery-django#525]
It would be appropriate to have a "Crisis" label for this ticket

We cannot create jobs if the "One Time" boolean is selected, which is a majority of our jobs. Image provided for clarification. 

![crisis](https://user-images.githubusercontent.com/41381131/44914956-a6361400-acff-11e8-8293-4a029556079b.png)

**Comment by bartmika** [comment]
@KPSbuttar This is a GUI issue, please fix asap

**Comment by bartmika** [comment]
@RaymondO55 Sorry for this, try now.

**Comment by RaymondO55** [comment]
Issue resolved.
Thanks team
