### ISSUE TITLE
Tasks and jobs related to Ongoing

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#526]
**Summary:**
Jobs that are Ongoing or tasks related to ongoing jobs do not show up in the Jobs/Tasks functions, or under the jobs list for the Associate. Please include these

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, may you please provide example links of where this is happening?

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, there was a bug found and fixed. May you please confirm and close issue when ready?
