### ISSUE TITLE
Delete duplicate client

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#527]
**Summary:**
Can we please delete this client? It is a duplicate
https://london.workery.ca/en/jobs/search/detail/17840/lite/?page=1?keyword=mcfee

**Comment by bartmika** [comment]
@rodolfomartinez I was not able to find any duplicates for the last name - https://london.workery.ca/en/clients/search/results/?given_name=&last_name=Mcfee&street_address=&telephone=&email_id= are you sure you would like me to delete this record?

**Comment by bartmika** [comment]
@rodolfomartinez I see, with incorrect spelling the duplicate is:

https://london.workery.ca/en/clients/search/results/?given_name=&last_name=mcphee&street_address=&telephone=&email_id=
