### ISSUE TITLE
Add a job for client from the client summary screen

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#528]
**Summary:**
It would be helpful to discuss how we could launch a job for a client from their summary screen - currently, we have to go back to add new job once we have already pulled up their file

**Comment by bartmika** [comment]
What do you think about adding a button here?

![screen shot 2018-09-05 at 11 23 26 pm](https://user-images.githubusercontent.com/5767602/45133397-fdeed800-b162-11e8-9d34-64f4b4d5b3fe.png)

If you are able to create the GUI element for this, I can write the code to handle it.

**Comment by bartmika** [comment]
@rodolfomartinez Another idea I have is this...

![screen shot 2018-09-05 at 11 26 55 pm](https://user-images.githubusercontent.com/5767602/45133459-4e663580-b163-11e8-9dae-f6275450db92.png)

**Comment by rodolfomartinez** [comment]
I think the second option works better - let me play with it

**Comment by bartmika** [comment]
@rodolfomartinez Sounds good, once you give me your final decision, I will implement. Thanks!

**Comment by rodolfomartinez** [comment]
@bartmika can we use a button similar to the ones at the bottom of URLs like this
https://london.workery.ca/en/jobs/summary/detail/24819/lite/?page=1

It should have a plus icon, white text, green background, and be labelled "Add Job"
