### ISSUE TITLE
FInancials > Complete But Unpaid - processing

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#534]
**Summary:**
Under the "Service Fee" read only field, can we add a field titled
Service Fee Paid
which populates with the same data as "Service Fee" but can be edited by the user.

Also, underneath this field, can we add a read only field called "Balance", which is equal to 
Service Fee - Service Fee Paid
(so instances where they are the same, it should be 0, this number can be negative, but regardless if positive or negative it should round to 2 digits - ie financial format).\
These two new fields should be saved to the data base.

**Comment by bartmika** [comment]
1. Under the ``Service Fee`` I will create a field called "Actual Service Fee Paid" (ASFP)

2. This ASFP field is editable

3. Update the retrieve pages to have this ASFP field.

4. Under this field I will create a `Balance` field

5. Make Balance field be read only

6. Do not save the read only field.

7. This balance field dynamically changes based on what people enter in other fields.

**Comment by rodolfomartinez** [comment]
@bartmika - yes. To clarify, item 7, balance, should be calculated as:
Service Fee - Actual Service Fee Paid

Balance should be recorded, and saved, and after data is saved, this should be the balance field the next time a job is being moved from completed and unpaid to completed and paid.

**Comment by bartmika** [comment]
@rodolfomartinez Progress so far.

> 1. Under the ``Service Fee`` I will create a field called "Actual Service Fee Paid" (ASFP)
Done

> 2. This ASFP field is editable
Done

> 3. Update the retrieve pages to have this ASFP field.
Done

**Comment by bartmika** [comment]
To create an ongoing balance for the associate, the following need to be done:

1. To me it sounds like every associate has a balance field in their record which is computed after completion of every job.

2. An ETL needs to be written which will retroactively go through all the work orders and compute the balance. These balances are interconnected, so for example, you land on "John Smith", you will need to get all his work orders starting from oldest to newest records and compute a balance.

3. Need to update the financials update page.

4. Need to update the financials retrieve page.

5. Need to do QA on system with this new feature.

**Comment by bartmika** [comment]
# Part 1

> Under this field I will create a Balance field

TODO


> Make Balance field be read only

TODO

> Do not save the read only field.

TODO

> This balance field dynamically changes based on what people enter in other fields.

TODO

# Part 2
> To me it sounds like every associate has a balance field in their record which is computed after completion of every job.

TODO


> An ETL needs to be written which will retroactively go through all the work orders and compute the balance. These balances are interconnected, so for example, you land on "John Smith", you will need to get all his work orders starting from oldest to newest records and compute a balance.

TODO


> Need to update the financials update page.

TODO

> Need to update the financials retrieve page.

TODO


> Need to do QA on system with this new feature.

TODO


> Associate retrieve page needs a balance amount displayed.

TODO

**Comment by bartmika** [comment]
@KPSbuttar Please update the GUI page for ``http://london.workery.ca/en/financials/unpaid-jobs/detail/24763/edit`` so the balance gets updated.

Computation is:

```
balance = service fee - actual paid
```

**Comment by bartmika** [comment]
@rodolfomartinez Please note the balance in job order is for the particular job, if you want to see the total balance for the associate then you'll need to go to the associate retrieve page.

**Comment by rodolfomartinez** [comment]
@bartmika - would it be possible for you to add this field? still no word from @KPSbuttar

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, I'll need to look at this tomorrow.
