### ISSUE TITLE
News Items should auto terminate

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#538]
**Summary:**
If a news item has a firm end date (ie associate is away until Oct 15) then at 12:01AM on the day of the notice, it should automatically end, making the associate available again.

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, ETL was created that runs 12:00AM dailey to auto-terminate away logs which have expired (if they have a date). Please confirm after today.
