### ISSUE TITLE
Process for jobs with a financial status

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#541]
**Summary:**
For jobs with "Complete but unpaid" or "Complete and Paid" status, can we change it so that clicking the "View" link goes to the financial portion of the job rather than the job summary? So clicking view for job #24674  would go to
https://london.workery.ca/en/financials/unpaid-jobs/detail/24674/

**Comment by bartmika** [comment]
@rodolfomartinez Task completed, may you please verify this works for your team?
