### ISSUE TITLE
Members > Jobs Tab

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#543]
**Summary:**
At URLs like this:
https://london.workery.ca/en/members/summary/detail/6138/jobs/?job_state=all

Can we replace the title text "View Associate Member" with the Associates name and phone number?

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, task completed. May you please confirm?

Thanks,

**Comment by rodolfomartinez** [comment]
Task complete.
