### ISSUE TITLE
Cannot View Job Summary once it is complete and paid/unpaid

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#546]
**Summary:**
Once a job is completed and paid, there is no way to get back to the job summary if you are a manager. This is related to #541 - 

Is it possible to implement logic where if a manager is at a URL like
https://london.workery.ca/en/financials/unpaid-jobs/detail/24854/?page=1
that cclicking the job hyperlink goes to the "normal" job summary screen

**Comment by bartmika** [comment]
@rodolfomartinez That is correct, once completed, you cannot see the details. I will have to add it in there as new feature.

**Comment by bartmika** [comment]
@rodolfomartinez Did not implement anything, previous tickets #545, #546, & #547 may have fixed this issue. Please review and close if issue has been resolved.
