### ISSUE TITLE
48 hour task moving jobs to completed but unpaid instead of 7 day follow up

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#549]
**Summary:**
When completing a 48 hour task jobs appear to be going straight to "complete but unpaid" status

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, I've fixed the bug, the 48h api endpoint was setting the state to `complete but unpaid`. I've updated the api endpoint so now it sets it to `in progress`. As a result `frontline staff` will be able to see the completion survey in the tasks lists. Please confirm.
