### ISSUE TITLE
Add Icon List view 

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#550]
**Summary:**
Can we implement the job summary and financial icons from this URL
https://london.workery.ca/en/jobs/summary/

at
https://london.workery.ca/en/members/summary/detail/6138/jobs/?job_state=all

and
https://london.workery.ca/en/pending-tasks/

and
https://london.workery.ca/en/financials/unpaid-jobs/
https://london.workery.ca/en/financials/paid-jobs/
https://london.workery.ca/en/financials/all-jobs/

**Comment by bartmika** [comment]
https://london.workery.ca/en/members/summary/detail/6138/jobs/?job_state=all
* Done

http://london.workery.ca/en/clients/summary/detail/23475/jobs/
* Done

https://london.workery.ca/en/pending-tasks/
* Cannot, not compatible.

https://london.workery.ca/en/financials/unpaid-jobs/
* TODO

https://london.workery.ca/en/financials/paid-jobs/
* TODO

https://london.workery.ca/en/financials/all-jobs/
* TODO

**Comment by rodolfomartinez** [comment]
@bartmika - understood, we can drop it for point 3

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, task has been completed. May you please confirm?
