### ISSUE TITLE
Clients to Delete

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#551]
**Summary:**
These clients have incomplete/inaccurate/duplicate records
https://london.workery.ca/en/clients/summary/detail/11935/lite/?page=1
https://london.workery.ca/en/clients/summary/detail/9999/lite/?page=1
https://london.workery.ca/en/clients/summary/detail/21578/lite/?page=1
https://london.workery.ca/en/clients/summary/detail/11273/jobs/
https://london.workery.ca/en/clients/summary/detail/5332/full/
https://london.workery.ca/en/clients/summary/detail/7913/jobs/
https://london.workery.ca/en/clients/summary/detail/12391/lite/
https://london.workery.ca/en/clients/summary/detail/11113/jobs/
https://london.workery.ca/en/clients/summary/detail/5332/jobs/
https://london.workery.ca/en/clients/summary/detail/19/jobs/
https://london.workery.ca/en/clients/summary/detail/4543/jobs/

**Comment by bartmika** [comment]
https://london.workery.ca/en/clients/summary/detail/11935/lite/?page=1
*  Deleted

https://london.workery.ca/en/clients/summary/detail/9999/lite/?page=1
* Deleted

https://london.workery.ca/en/clients/summary/detail/21578/lite/?page=1
* Deleted

https://london.workery.ca/en/clients/summary/detail/11273/jobs/
*  Deleted

https://london.workery.ca/en/clients/summary/detail/5332/full/
* Deleted

https://london.workery.ca/en/clients/summary/detail/7913/jobs/
* Deleted

https://london.workery.ca/en/clients/summary/detail/12391/lite/
* Deleted

https://london.workery.ca/en/clients/summary/detail/11113/jobs/
* Deleted

https://london.workery.ca/en/clients/summary/detail/5332/jobs/
* 

https://london.workery.ca/en/clients/summary/detail/19/jobs/
* 

https://london.workery.ca/en/clients/summary/detail/4543/jobs/
*

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, task has been completed. May you please verify.
