### ISSUE TITLE
New Report - Leads by Skills

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#552]
**Summary:**
Need to create a new report that will have a to/from assignment date range, a text field to type a skillset, and job status dropdown (first option should be all). Report template sent via email

**Comment by bartmika** [comment]
@rodolfomartinez Hi Rodolfo, I've created this new report. Just an FYI, I slightly formatted the columns. Please confirm this minor modification is acceptable and this CSV report generator is acceptable.
