### ISSUE TITLE
Date Entry UI Broken

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#556]
**Summary:**
With the most recent fix to this UI, the date entry field became read only, so importing older years means that you have to manually click back. 

Samnple URL:
https://london.workery.ca/en/clients/create/residential

I need to be able to use both date picking widget AND text entry with working validation

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hello sir, This is completed you can still can't write in text field instead best part is now you can directly select YEAR and MONTH from the DROPDOWN in datepicker feature. So their will be no issue regarding date formats.

Please review ALL thanks!
