### ISSUE TITLE
Stepped Navigation

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#558]
**Summary:**
Please implement stepped navigation from #515 here

https://london.workery.ca/en/pending-tasks/4468/activity-sheet/
(assignment sheet)
https://london.workery.ca/en/pending-tasks/4280/?page=1
(48 hour follow up)
https://london.workery.ca/en/clients/create/residential/confirm
(create residential Job - also apply to commercial job)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its completed sir. Thanks
