### ISSUE TITLE
Add "Files" Tab to UI for jpobs, clients, members, partners, staff "lite" view

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#560]
**Summary:**
For these URLs
https://london.workery.ca/en/clients/summary/detail/9/lite/?page=1
https://london.workery.ca/en/members/summary/detail/6138/lite/?page=1
https://london.workery.ca/en/staff/summary/detail/8/lite/?page=1
https://london.workery.ca/en/partners/summary/detail/8/lite/?page=1
https://london.workery.ca/en/jobs/summary/detail/25141/lite/?page=1

Add an extra button at the end call "File" with FA icon "file-open"

**Comment by rodolfomartinez** [comment]
Great, but Icon should be "folder-open"

**Comment by rodolfomartinez** [comment]
@KPSbuttar - please review

**Comment by rodolfomartinez** [comment]
@KPSbuttar need to update to folder-open icon and add to sub pages like
https://london.workery.ca/en/members/summary/detail/6138/activity-sheets/

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hello sir, Finally This issue is resolved for All jobs, staff, partners, members and clients modules all urls creation, Files page template coding and linking to Files tabs all work completed. Please review everything. Thanks.
