### ISSUE TITLE
Create "Files" page UI

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#561]
**Summary:**
We need to create a UI for the "files" page - it should look as close as possible to existing pages. It needs the following:

1. Two nice buttons - one that says upload (it should have the cloud icon and then the word "Upload"), and the second one should have a disk icon and say "Save".

Clicking Upload should open a nice jquery style popup file uploader, which is responsive and works on mobile devices. The uploader should have 3 fields:
a) (read only) filename
b) Title: (textbox) where user can input up to 30 characters as a title
c) Type: (dropdown) should have the following options
- Contract
- Image
- Insurance Certificate
- Police Check
- License
- Other

2. Until a file has been selected and uploaded, save button should be "greyed" out

3. Beneath, there should be a table (use past UI) with the following columns

Title     Description     Type

4. Entries should have one icons - (similar to job view list at https://london.workery.ca/en/jobs/summary/)

1st icon - magnifying glass - this allows to view/download the file

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez  hi sir can you create **files** blank pages and set urls all django work where i have to put UI design in all directories mentioned in #560 

Thanks

**Comment by rodolfomartinez** [comment]
@bartmika - can you please review this and reassign to me once the page is viewable on prod?

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez I have already added page in django files and url is working now will upload new page UI design. Thanks

**Comment by KPSbuttar** [comment]
@rodolfomartinez Hi sir, good morning. This TASK is done you can view new UI design here at live site https://london.workery.ca/en/clients/summary/detail/9/files/

Please review new design and @bartmika sir you can now complete this UI by adding functionality to this page. Thanks

Regards
@KPSbuttar
