### ISSUE TITLE
In financials we want to break out the material and labour in financials. 

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#577]

**Comment by bartmika** [comment]
@rodolfomartinez Task completed, may you please confirm the page?

**Comment by rodolfomartinez** [comment]
https://london.workery.ca/en/financials/unpaid-jobs/detail/25224/?page=1

(@bartmika - please review to see if @KPSbuttar can handle this)

At this URL, the "Original Quote" field should be removed, and the rows should be re-ordered as follows:
AFTER invoice ID#(order of rows before this is fine)
1. Quoted Labour
2. Quoted Materials
3. Total Quote
4. Actual Labour
5. Actual Materials
6. Total Tax
7. Total
8. Service Fee
9. Service Fee Payment Date
10. Actual Service Fee Paid
11. Account Balance

**Comment by bartmika** [comment]
@rodolfomartinez Yup @KPSbuttar can do this.

@KPSbuttar Don't forget to update the Ajax call along with the HTML when editing this.

**Comment by KPSbuttar** [comment]
Its done sir can you please review @rodolfomartinez @bartmika Thanks
