### ISSUE TITLE
total quoted sum

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#580]
Hi @KPSbuttar,

May you please write a calculator in the `total quoted` field to sum `quoted labour` and `quoted material`. Please make sure the `total quoted` field is read only and is dynamically computed as the user enters those two fields.

![screen shot 2018-11-22 at 9 55 48 pm](https://user-images.githubusercontent.com/5767602/48927113-89921e00-eea1-11e8-8085-5e2a6ed56ae1.png)

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Its completed sir, please review all. Thanks
