### ISSUE TITLE
Financial Summary Screen

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#581]
https://london.workery.ca/en/financials/unpaid-jobs/detail/25224/?page=1

At this URL, the "Original Quote" field should be removed, and the rows should be re-ordered as follows:
AFTER invoice ID#(order of rows before this is fine)

Quoted Labour
Quoted Materials
Total Quote
Actual Labour
Actual Materials
Total Tax
Total
Service Fee
Service Fee Payment Date
Actual Service Fee Paid
Account Balance

**Comment by bartmika** [comment]
@rodolfomartinez Confirmed @KPSbuttar can do this.

**Comment by bartmika** [comment]
@KPSbuttar Kawnar, don't forget to update the ajax function along with the HTML when you modify this. Thank you.

**Comment by rodolfomartinez** [comment]
@KPSbuttar - the field order display is incorrect - please review:
https://london.workery.ca/en/financials/unpaid-jobs/detail/25224/?page=1

At this URL, the "Original Quote" field should be removed, and the rows should be re-ordered as follows:
AFTER invoice ID#(order of rows before this is fine)

Quoted Labour
Quoted Materials
Total Quote
Actual Labour
Actual Materials
Total Tax
Total
Service Fee
Service Fee Payment Date
Actual Service Fee Paid
Account Balance

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its fixed all done sir in edit screen as well. Please review.
