### ISSUE TITLE
Financials Not Working

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#584]
**Summary:**
At this URL
https://london.workery.ca/en/financials/all-jobs/detail/25224/edit

Actual Labour was inputted as $50
Actual Materials was inputted as $4

Total is $50 - Actual Materials is NOT carrying in
![272eefae-7d10-443f-9735-ce4e9f3f0417](https://user-images.githubusercontent.com/7537946/50161627-55e0c300-02aa-11e9-9859-9f9325b8d51f.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez hi sir its done. Please review, thanks
