### ISSUE TITLE
Icon error?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#588]
**Summary:**
At this URL
https://london.workery.ca/en/members/summary/detail/6097/jobs/?job_state=all

icons for Skill sets and Staff do not load

**Comment by rodolfomartinez** [comment]
![fb6c3fb0-358c-478f-a408-81c01ababd3e](https://user-images.githubusercontent.com/7537946/51205474-00f99200-18d4-11e9-9d10-ad3f1f020a90.png)

**Comment by KPSbuttar** [comment]
@rodolfomartinez Its done sir please review, thanks
