### ISSUE TITLE
Gender

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#594]
**Summary:**
Create list of names to assign gender for null values

**Comment by rodolfomartinez** [comment]
@KHynds - along with volunteers, can you create a list of the 10-20 most popular names for males and females, so we can create a script to populate gender?

**Comment by KHynds** [comment]
@rodolfomartinez Will do.

**Comment by KHynds** [comment]
[Top 20 Male & Female Names from 1970.docx](https://github.com/over55/workery-django/files/2946177/Top.20.Male.Female.Names.from.1970.docx)

**Comment by rodolfomartinez** [comment]
Emailed list of names, variants and gender

**Comment by rodolfomartinez** [comment]
@bartmika - google doc with names shared

**Comment by rodolfomartinez** [comment]
@bartmika can you confirm that google doc for gender ETL was received?
