### ISSUE TITLE
Associate/Staff/Customer previously selected Province/Country not selected

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#595]

**Comment by bartmika** [comment]
Hi Kanwar (@KPSbuttar), for this ticket, it appears when we save a region/country, it saves successfully, but when you go to the update, the jQuery code does not select the previously selected choice. May you please investigate and fix for the:
- customer update
- staff update
- associate update
- partner update

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Hi sir, finally this bug is fixed for all modules and update pages after so many efforts it was hard to find the error taken time but some how all fixed now completely. Please review ALL done. Thanks
