### ISSUE TITLE
New Ongoing Jobs - Survey Task

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#598]
**Summary:**
At this URL
https://london.workery.ca/en/pending-tasks/6885/?page=1
I completed the 48 hour follow up immediately and the 7 day follow up/survey was created for the day after the follow up - is this because the ongoing job is scheduled to end the 31st? or is it a bug? I expected around Feb 5.

**Comment by bartmika** [comment]
@rodolfomartinez May you please confirm?
