### ISSUE TITLE
Cannot terminate ongoing job?

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#600]
**Summary:**
On the details screen from the dropdown, I cannot terminate job. Neither cancel nor update buttons seem to work. Is this a GUI or validation error? Also, could this just use buttons w/a modal instead of a dropdown for status?
https://london.workery.ca/en/ongoing-jobs/summary/detail/168/edit/

**Comment by bartmika** [comment]
@rodolfomartinez May you please confirm?
