### ISSUE TITLE
Associate Dashboard

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#603]
@rodolfomartinez Please write down the details of how you envision the associate dashboard pages to work.

**Comment by rodolfomartinez** [comment]
First, we would need to

**Comment by rodolfomartinez** [comment]
The Associate Dashboard would be a very stripped down version of what staff would see. Basically Associates would see their own profile card/page, they would only have two tabs:
1. Summary
2. Jobs tab - client data would not be "clickable" to protect clients contact info.  Job summary link would take to job summary, but clients phone would not display and name would not be clickable. Financials column would not exist. 
3. *new function*
Invoices - clicking this would have a list of downloadable PDFs of invoices generated from financial data
