### ISSUE TITLE
Segment out associates with expired police check

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#612]

**Comment by bartmika** [comment]
Hi @rodolfomartinez @SusanFaiarley @KHynds, this code will significantly affect your business operation - a lot of associates will be set to unavailable. Please discuss with yourselves how to handle getting more associates to have police checks before I will implement this code.

**Comment by rodolfomartinez** [comment]
yes, we will discuss this first. Thanks

**Comment by rodolfomartinez** [comment]
@bartmika - I think we will implement this in 30 days - want to give our processes some time to catch up to this, but it is still a necessary feature.

**Comment by rodolfomartinez** [comment]
@bartmika - we are nearly ready to implement, Can discuss soon
