### ISSUE TITLE
Add New Client Doesn't Allow Special Characters

### ISSUE THREAD

**Issue by KHynds** [over55/workery-django#628]
Trying to input a client with the last name "O'Neil" the system throws an error when trying to save, due to the apostrophe.

**Comment by bartmika** [comment]
Hi @KHynds, I believe we put this code in place recently because it affected the CSV outputs in reports. I will have to remove the recent code that was submitted that prevents specials charavters. I will submit the code and have it ready for your team by this monday. Thank you!

**Comment by KHynds** [comment]
Hi @bartmika, is there a way around it affecting CSV outputs, while still allowing, at the very least an apostrophe.

**Comment by bartmika** [comment]
Task completed.
