### ISSUE TITLE
Pending Tasks UI

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#629]
**Summary:**
Whenever this screen is refreshed, the order of jobs changes, so if two staff members want to tackle tasks (say one starts at the bottom and another at the top) then it becomes complicated since they could be working off of the same clients but in two different orders.

Perhaps migrating this component to react could allow for something that updates in real time ? Because currently as a task is closed, other staff members on the same page will not see this unless if they refresh

Feel free to contact for more details.

**Comment by bartmika** [comment]
@rodolfomartinez Added ability to filter in ascending or descending order when clicking the table row header. I believe this solution will fix your teams workflow! 👍 

FYI @RaymondO55 @KHynds @SusanFaiarley
