### ISSUE TITLE
Inputting quotes closes the job as completed but unpaid.

### ISSUE THREAD

**Issue by KHynds** [over55/workery-django#631]
When you input a quote, (work not complete, prior to job) you are required to pick either paid, or unpaid, as a required field. If you proceed with the job marked unpaid, with a quote, but no actual information otherwise, the job is closed as completed but unpaid, and taken off the tasks page.

**Comment by soyong20161205** [comment]
Hello, I have a question.
so, I don't understand the content of the ticket as well.

**Comment by soyong20161205** [comment]
Hello, I have a question.
so, I don't understand the content of the ticket.
![Screenshot from 2019-05-23 04^%45^%26](https://user-images.githubusercontent.com/40175691/58250457-a5f90f80-7d8b-11e9-9350-26f5f415a8d0.png)
![Screenshot from 2019-05-23 04^%45^%34](https://user-images.githubusercontent.com/40175691/58250471-abeef080-7d8b-11e9-98aa-c7bf01dc9051.png)

**Comment by soyong20161205** [comment]
you mean that job finacials editing page or I have to create the new page?

**Comment by soyong20161205** [comment]
and then I don't understand the meaning of this sentence "If you proceed with the job marked unpaid, with a quote, but no actual information otherwise".

**Comment by soyong20161205** [comment]
so, can you explain more detail about this?

**Comment by soyong20161205** [comment]
Oh, I see.
Now I understood.
