### ISSUE TITLE
Tax not entering into calculations

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#640]
**Summary:**
On the financials screen, Taxes is not inputting into the total amount. Job #21770 is an example

**Comment by bartmika** [comment]
I thought @KPSbuttar fixed this issue?

**Comment by bartmika** [comment]
@soyong20161205 Hi Kham, can you investigate this problem and fix it?

**Comment by rodolfomartinez** [comment]
@soyong20161205 - update?

**Comment by soyong20161205** [comment]
I have completed the ticket #640.
