### ISSUE TITLE
Why is join-date not being set during client creation?

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#643]

**Comment by rodolfomartinez** [comment]
@bartmika @soyong20161205 can you please clarify this ticket?

**Comment by soyong20161205** [comment]
I have set join-date during client creating.

**Comment by rodolfomartinez** [comment]
@bartmika - update?

**Comment by soyong20161205** [comment]
what do you mean?

**Comment by rodolfomartinez** [comment]
@khynds @RaymondO55 please QA

**Comment by KHynds** [comment]
@rodolfomartinez QA'd. The form has an asterisks next to "join date" making me assume it's a required field.

However, it is not a required field, and you can progress without inputting it.

Assign @soyong20161205 to the job, and he can fix it.

**Comment by rodolfomartinez** [comment]
@bartmika please review and if necessary move to workery-front

**Comment by rodolfomartinez** [comment]
@bartmika is Join date the date when the client was added to workery? If so, this should be set by the system, and should not appear during client add, but could be editable later by staff.

**Comment by bartmika** [comment]
@rodolfomartinez This issue has been fixed by the https://github.com/over55/workery-front rewrite, as a result, I will not implement any fixes.
