### ISSUE TITLE
Required Field for Gender not Required on Intake

### ISSUE THREAD

**Issue by KHynds** [over55/workery-django#647]
Gender is only a requirement on the client's page when you go into edit the client's details.

Not on the original page when a client's data is first entered into the database.

**Comment by soyong20161205** [comment]
I have completed the ticket #647.

**Comment by RaymondO55** [comment]
@soyong20161205 This ticket is incomplete. As mentioned before, the [Gender] field does not exist on the client intake form. I should be a required field as it is on the client edit form. 
![EditGenderField](https://user-images.githubusercontent.com/41381131/58720006-0ba65680-839f-11e9-80df-741ed97b9dce.png)
![Intake No Gender Field](https://user-images.githubusercontent.com/41381131/58720009-0e08b080-839f-11e9-94f7-bf438a687c1e.png)

**Comment by soyong20161205** [comment]
I have just revised the ticket #647 of workery-django project.
Please check it.

**Comment by soyong20161205** [comment]
And then I have pushed the changed code on the master branch.
Please check it.

**Comment by KHynds** [comment]
@RaymondO55 ticket should be re-opened. When you create a new client, even though the gender field is a requirement, it's not saved on the client's profile page.

**Comment by RaymondO55** [comment]
@soyong20161205 As Kristian reported, the gender field is not saving the selection value correctly. Images of testing provided.
![GenderClientCreation](https://user-images.githubusercontent.com/41381131/59043115-ab556000-8849-11e9-9e20-5dce1dec111d.png)
![GenderNotSaving](https://user-images.githubusercontent.com/41381131/59043131-b01a1400-8849-11e9-8736-649558e6ded3.png)

**Comment by soyong20161205** [comment]
I have just fixed the saving error in gender field in workery-django.

**Comment by soyong20161205** [comment]
and then I have just pushed the changed code.
please check it.

**Comment by KHynds** [comment]
QA'd, working as intended. Closing.
