### ISSUE TITLE
Invoice - Visits Fields

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#649]
**Summary:**
At this URL
https://london.workery.ca/en/financials/unpaid-jobs/detail/26210/edit

The # of visits input field should become an arrow up/down, with a maximum value of 30

**Comment by bartmika** [comment]
![Screen Shot 2019-06-22 at 9 59 26 PM](https://user-images.githubusercontent.com/5767602/59971218-d7f5c100-9545-11e9-9111-86de5929efc7.png)

I see it already has it.

Would it be better if we create a dropdown instead with 1 to 30 options?

**Comment by rodolfomartinez** [comment]
@bartmika ok this is what we needed. closing
