### ISSUE TITLE
When Assigning Skill Sets To a New Job, The System Should Pull People with Both.

### ISSUE THREAD

**Issue by KHynds** [over55/workery-django#654]
Currently when assigning a job with multiple skill sets, the system is currently using a OR gate, whereas an AND gate would be more beneficial.

E.G.

If we need an associate who can do both parging & electrical for a job and assign both skill sets, what the system currently does is pull everyone who has either parging, or electrical.

Whereas,

What we want is for Workery to only show us associates with both parging AND electrical.

**Comment by KHynds** [comment]
@rodolfomartinez We discussed this briefly a few weeks ago, and Nakour in the office is bringing it up. Can we get Bart working on this?

**Comment by rodolfomartinez** [comment]
@khynds but what happens if we do not have someone with both? Do we need to consider splitting jobs into two?

**Comment by KHynds** [comment]
@rodolfomartinez If we don't have someone with both, staff can see that, and then split the job. We would be able to use skill tags more liberally, setting painting & drywall to stop from wasting anyone's time calling Brad Gray for example.

If we notice we have nobody with both skills, then we would be able to coordinate.
