### ISSUE TITLE
"Commercial Insurance Expired" Does Not Remove Associates From Being Assigned New Jobs

### ISSUE THREAD

**Issue by KHynds** [over55/workery-django#657]
The system automatically setting an associate away due to out of date insurance (or police check, which is another bug, it should be separate from commercial insurance) does not remove them from available associates when assigning new jobs.

**Comment by bartmika** [comment]
@rodolfomartinez  @KHynds Fixed issue with the system selecting **commercial expiry** instead of the **policy expiry** in the away messages.

Now in regards to expired associates, can you provide how to replicate this issue when adding new jobs? Thanks

**Comment by rodolfomartinez** [comment]
@KHynds - please clarify the process for reproducing this bug

**Comment by KHynds** [comment]
@rodolfomartinez @bartmika 

Every single associate who is on the away list due to commercial insurance, or police check can still be assigned jobs. It's just become much more apparent with so many away due to police checks.

![Paul McDonnell Assign Associate](https://user-images.githubusercontent.com/48287576/60103122-11d4ec00-972d-11e9-9cc8-bf1c3d94541e.png)
![Paul McDonnell Away List](https://user-images.githubusercontent.com/48287576/60103132-14cfdc80-972d-11e9-9aac-3ac33d500451.png)


As you can see, despite Paul being on the away list due to no up to date police check/waiver, we can still assign him to new jobs. It's like this for every single person who is away either for a police check, or commercial insurance.

Manually setting people to away works perfectly. The system automatically triggering it does not, however.

**Comment by bartmika** [comment]
@KHynds Hi Kristian, thank you for the details, this helped fix the problem! Indeed there was a bug in the automatic system, I've updated it and applied the bugfix patch to worker. 

May you please confirm this issue is fixed on your end and close this ticket if confirmed fixed? Thanks again for your help!
