### ISSUE TITLE
Financials > Create Invoice - Invoice Date Not Updating When Changed in Financials

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#691]
**Summary:**
When creating an invoice here
https://london.theworkery.ca/financial/20336
If the invoice date has been change in the financials details screen, it does not pull in the new date. It should be 08/11/2016 instead it pulls in 08/10/2016

**Comment by rodolfomartinez** [comment]
@bartmika could this be related to a chron job?

**Comment by rodolfomartinez** [comment]
or is it related to how the system handles dates/times (utc)?

**Comment by rodolfomartinez** [comment]
@bartmika - this issue is still present

**Comment by rodolfomartinez** [comment]
For job 20997 the invoice date from financials should be 01/25/2017 - as before it goes back a day for some reason.
![Screen Shot 2021-07-11 at 8 38 00 PM](https://user-images.githubusercontent.com/7537946/125215212-baa90200-e288-11eb-927c-c6bc551bfe81.png)

**Comment by bartmika** [comment]
Confirmed bug fix for that screen.
