### ISSUE TITLE
Add Staff Member - password validation enforcement

### ISSUE THREAD

**Issue by rodolfomartinez** [over55/workery-django#78]
**Summary:**
When adding a new team member, the password validation was enforced at the summary screen. This lead to the summary screen, with the validation error being displayed at the top (see the error in the image below).

This can be confusing for the user; is it possible to enforce the validation on the form screen so that the user cannot see this screen unless if there are 0 validation errors?

![5a3b325c-1b83-4abd-bd1a-9d320004264c](https://user-images.githubusercontent.com/7537946/39397524-a2a4ef48-4ace-11e8-9106-b9e55c153048.png)

**Comment by rodolfomartinez** [comment]
@bartmika - is this an issue for @KPSbuttar ? If so, please remove yourself as an assignee. Thanks

**Comment by bartmika** [comment]
The API endpoint would already handle it in the create/edit page. @KPSbuttar just needs to make the GUI support it.

**Comment by KPSbuttar** [comment]
@rodolfomartinez @bartmika Its done
