### ISSUE TITLE
Better Form Error Handling

### ISSUE THREAD

**Issue by bartmika** [over55/workery-django#80]
Implement for:

# Customers

* 1. Add Residential Customer

* 2. Add Commercial Customer

* 3. Update Customer

* 4 Add Comments

# Associates

1. Add Associate 

2. Update Associate

3. Add Comment

# Staff

1. Add Staff

2. Update Staff

# Partners

1. Add Partners

2. Update Partners

3. Add comments.

# Profile Page

1. Update profile page.

**Comment by bartmika** [comment]
For me to close this issue, I will need to have this issue finished: (1) https://github.com/MikaSoftware/inthought/issues/89 by @rodolfomartinez  and then I can proceed further. I think Kanwar can implement this as well as it's purely CSS/JS/HTML code.

Secondly, I will need to make sure the fields have proper error messages when the error is received from the API. I think we might need to get Kanwar to implement this. Inside the code I've placed `TODO` comments.

**Comment by rodolfomartinez** [comment]
I have given my feedback on InThought # 89, so @KPSbuttar please proceed.

**Comment by bartmika** [comment]
@KPSbuttar  Hi Kanwar, I am having difficulty implementing this code, I don't know if you updated the github repo b/c when I look http://inthought.pw/clients/client_add.html I see your most recent code but when I look at the repo https://github.com/MikaSoftware/inthought/blob/master/html/clients/client_add.html I don't see your code.

Can you check your code again, or better, may you please implement the validation generation as an example in this projects "residential -> create" page.

@rodolfomartinez FYI

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hello sir, for this issue firstly sry n yes i didn't uploaded latest code in INTHOUGHT repo which is done now you can copy UI codes from here: https://github.com/MikaSoftware/inthought

ALSO sir i have implemented that Validation UI in "residential -> create" main project as you ASKED me to add, you can see in my latest commit here.

ONLY thing for which i need your help @bartmika  sir for this page as you can see in front end error function gives "given_name" as prop from err JSON but we need field name as well like "First name" or "Last name" not like "last_name" etc if you can make inner html text as field name and make prop "given_name" etc as error div "id=".

Rest ALL done. YOu can copy codes from INTHOUGHT project and implement.

Thanks!

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, if you get an error for "given_name", sometime you may have to use "first_name" fields instead.

I have re-opened this ticket and will close it again once every page has this error validation pattern working.

**Comment by bartmika** [comment]
@KPSbuttar I would like to task you Kanwar with going through all the forms and add your latest code which will generate that red error prompt box for any errors received by the API web-service, and I want you to make sure the fields have the individual errors applied as well.

@rodolfomartinez May you please QA Kanwars work to confirm this error prompt message exists in all the GUI - you will be testing the **create** and **update** pages.

**Comment by KPSbuttar** [comment]
@bartmika HI sir, no id didn't meant that its just error text i m talking about. For example: currently when error comes lets say for name, so error displays as:
" given_name: This field may not be blank. " but i guess " Given Name: This field may not be blank. " thats all i was saying in my last message, so you see that underscore ids needs to be removed i guess. like " is_ok_to_email: Message" in error MESSAGE will be as "Is ok to email: Message" and so on. 

 I hope you getting my point.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Also sir can you please explain this a little more: 

"generate that red error prompt box for any errors received by the **API web-service**, and I want you to make sure the fields have the **individual errors** applied as well."

**Comment by bartmika** [comment]
@KPSbuttar Hi Kanwar, I have attached this screenshot showing what I would like to happen. When an error is generated by the API web-service, I'll need you to (1) generate an error box and (2) Make the individual field error. Please let me know if this picture makes sense.

![screen shot 2018-05-06 at 7 04 50 pm](https://user-images.githubusercontent.com/5767602/39678772-9f9dc9da-5160-11e8-993e-7e0eb82adfa1.png)

Now if I understand correctly, you are wondering what the error text will be? Please make the error text always be from the **API web-service**. So for example if server says "Cannot be blank", then you output "cannot be blank" to both (1) the error box and (2) the individual erring field.

**Comment by bartmika** [comment]
@KPSbuttar Exactly! You might be wondering why? The reason is because this is good **user experience (UX)** and is considered a best practice for form validation. This is an important task too so please make sure you implement this. Thank you and if you have any more questions please let me know.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir, Finally this is done for "ADD Residential Client" page. Please refresh server so i can check this page LIVE if all worked properly. Then will finalize and IMPLEMENT IT over all other forms. Thanks

**Comment by rodolfomartinez** [comment]
I can confirm that this works, however it would be nice to have the errors human readable. For example, instead of last_name or street_address ask the user to fill in the fields by label - i.e. Last Name, Street Address. See attached screen
![aedcff80-f07d-4546-8ee2-1121758cb65c](https://user-images.githubusercontent.com/7537946/40030371-394aeb00-57b8-11e8-8aea-0fe05c6e65e9.png)

**Comment by bartmika** [comment]
1. Hi @KPSbuttar can you add code in the Javascript code where we can replace the "last_name", "is_ok_to_email" fields be replaced with some custom readable text?

2. I will update the body of this ticket to list everything that needs to be done - once all items are crossed out this ticket is considered closed.

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Ok sir i will do all these changes and implement to all forms mentioned above. 

Regarding 1st point i asked before to brat sir(@bartmika ) regarding this above to update API "prop" message. This is lil complex one to get labels in api errors. So need to find tricky way sir to add label text in FOR LOOP for API errors. 

If @bartmika sir you can check and suggest me as well.

Thanks, Will finish all ASAP!

**Comment by KPSbuttar** [comment]
@bartmika @rodolfomartinez Hi sir, Finally this is complete for all forms you mentioned above point 1 regarding human readable text also complete everywhere. 
You can Review all now and suggest me more TWEAKS to do if any.

Also sir PLEASE refresh server and base css also to make all changes visible in live project before you review all.

Thanks
